### ISSUE TITLE
table balancing

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#10]
mb2 has hooks to make table balancing and breakdown quick and painless, but I'd like to get some of the code I've already written play tested at single tables before I write and turn on the remaining pieces.

This is the last piece of semi-finished "major" functionality I want to complete before turning to stakeholders to guide my priorities.

**Comment by ctm** [comment]
I haven't touched this issue for a while in part because we have had so few play testers it hasn't been needed. Well, that's no longer the case, so I'll do a hack-and-slash implementation later today or tomorrow so that if we have more registrants than a single table holds, we can still play. I'll cut some corners and then fix those corner cases in the following days.

So, initially I'll just do a test whenever a player busts and if the number of players left will fit on fewer tables than are in play, I'll break that table and redistribute the players to the other tables. That is optimal (I think) for N+1 and N+2 players where N is the max number of players who can play. As the number of players increases, the possibility that we get unbalanced tables increases, ...

**Comment by ctm** [comment]
I chose to get #87 to a nice stopping point before doing this. There's a little bit of overlap and I really didn't want to have to deal with an ugly merge if I had done this first.

**Comment by ctm** [comment]
FWIW, table breakdown is working although it's lightly tested and observers of a given player don't move to the new table.

I'm not going to put the new version up tonight, so we'll start EASTER when we get 8.  I'll do some more clean-up and testing and we should have multi-table running tomorrow.

**Comment by ctm** [comment]
Oh, here are some corners I cut. I'll check the boxes when I fix the corner.

- [ ] `MovedTo` doesn't have an English translation
- [ ] `MovedFrom` doesn't have an English translation
- [ ] I'm not sure what happens when players come in between the blinds, but it's probably not right
- [ ] Observers of a player aren't moved to the new table
- [ ] When a table is broken, there's no explicit message to that table (just a bunch of MovedTo)
- [ ] No attempt to use players' relationship to the button when moving them
- [ ] We don't balance tables; we only break tables
- [ ] The table we break is the table that lost a player
- [ ] Only **very** lightly tested

**Comment by ctm** [comment]
FWIW, JADC took the big blind at a table that busted and then had to pay the big blind again at his new table. This issue needs some love.

**Comment by ctm** [comment]
I got some excellent advice from C. Meck via email. I'm pasting big blocks of it here. I've also updated my comment from April 13th to show that there's not really _that_ much more that needs to be done here.

Regarding breaking tables:

> ...  In a live tournament, when your table is broken, typically the tournament director brings seat cards for the empty seats and you receive one of these cards randomly (i.e. I get a card for Seat 3 at Table 2 and move there).  Sometimes you get unlucky and get the blinds twice in a row, sometimes you get lucky and get the button twice in a row.  There's really no way around this, it's just the nature of tournament poker and I'll be surprised if none of the BARGErs bitches about this when they get an unlucky table break.
>
> https://www.pokertda.com/view-poker-tda-rules/   See Rule 10 

Regarding balancing tables:

> Balancing tables:  It seems to me that this is likely going to be the hardest part to code.  Many poker players hate playing short and will be screaming for more players as soon as a player busts at their table.  I remember when Paul Campbell was Binion's TD and did our tournaments (he's now at Aria and is considered one of the top poker tournament  directors in the field), he would state that as long as you were within 2 players, it was OK to continue and he wouldn't move a player in that situation. 
>
> So if we are playing 9-handed NLHE and our table is down to 7 players, that's OK, no reason to move a player to our table.  If the table was down to 6 players, then there would be a reason to move a player.  It is usual to move a player from a full table that was due to be the big blind on that table's next hand to the new table, to assume the worst position (as that's what was going to be the situation if they weren't moved).  [snip]
>
> https://www.pokertda.com/view-poker-tda-rules/   See Rule 11
>
> Two Tables Left:  I'd suggest keeping tables balanced within one player at this point.  So, if one table has 9 players and the other table has 7 players, do move a player to get it to 8 & 8.

Regarding the final table:

> Final table:  I recommend a full redraw for position and the button when a final table is reached. Pretty standard in live play.

**Comment by ctm** [comment]
At this point, this is the only BARGE pre-requisites issue that isn't high priority. That's because this one is neither so easy that I can do it in between other things, nor does it require any significant refactoring or new technology. It's pretty much a "just grind it out" ticket.

WIth nine days to do four and a half issues (#225 is well more than half way completed), I think there's a chance I'll meet my self-imposed deadline. We don't even leave to Silverton until the 6th, so that's five days of buffer before my internet access gets complicated.

**Comment by ctm** [comment]
I added the code for combining the final table, redrawing for position and redrawing the button. I haven't tested it yet. I also thought a bit about the remaining items and should be able to code them up tomorrow.

**Comment by ctm** [comment]
Did a test with 40 w/o incident. Then did a test with 100 and ran into trouble. I suspect the trouble had to do more with my test harness, in that I multiplex all the tables through a single player and I _suspect_ that can result in weird session reuse that is impossible otherwise.

Specifically, during the 100 player test I wound up with a client crashing due to the nick being None. I also had mb2 crash with this panic:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', mb2/src/mb2/nick_mapper.rs:1109:66
stack backtrace:
   0:     0x561d869e26e5 - backtrace::backtrace::libunwind::trace::h34afbfad7fd770fc
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x561d869e26e5 - backtrace::backtrace::trace_unsynchronized::h460d522b1619a600
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x561d869e26e5 - std::sys_common::backtrace::_print_fmt::ha45fac10086813b4
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x561d869e26e5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hde84f63fcfd0e6de
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x561d86a0aebc - core::fmt::write::h540ac4a6a1232abc
                               at src/libcore/fmt/mod.rs:1076
   5:     0x561d869dbe42 - std::io::Write::write_fmt::hc344eafd6e850b4d
                               at src/libstd/io/mod.rs:1537
   6:     0x561d869e4d70 - std::sys_common::backtrace::_print::h4db88ff15cb5d61d
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x561d869e4d70 - std::sys_common::backtrace::print::h5fc39e1b1f610bd3
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x561d869e4d70 - std::panicking::default_hook::{{closure}}::h59e55edacb1d974a
                               at src/libstd/panicking.rs:198
   9:     0x561d869e4abc - std::panicking::default_hook::heee4c8016dfbf328
                               at src/libstd/panicking.rs:217
  10:     0x561d869e53b3 - std::panicking::rust_panic_with_hook::h8405b6301c79fb5a
                               at src/libstd/panicking.rs:520
  11:     0x561d869e4fab - rust_begin_unwind
                               at src/libstd/panicking.rs:431
  12:     0x561d86a08b71 - core::panicking::panic_fmt::h78830ea6a34e7206
                               at src/libcore/panicking.rs:85
  13:     0x561d86a08abd - core::panicking::panic::h68e56c2eeba99c8c
                               at src/libcore/panicking.rs:50
  14:     0x561d86652e5f - core::option::Option<T>::unwrap::h99d28082fedccb19
                               at /rustc/16957bd4d3a5377263f76ed74c572aad8e4b7e59/src/libcore/macros/mod.rs:10
  15:     0x561d86652e5f - mb2::mb2::nick_mapper::NickMapper::moved_from_to::h56e7dab76c6229d1
                               at mb2/src/mb2/nick_mapper.rs:1109
```

It's too close to the evening tournament for me to continue, but I definitely need to do more on this. There should be no errors.

From a performance standpoint, I currently have all the players creating new window, so that and bandwidth into my house makes for a pretty big pause at the start. I'll look at the database numbers tomorrow.

Overall, I'm _fairly_ happy with how the stress testing is going. The downside is that time spent stress testing is time I'm not working on fun features.

**Comment by ctm** [comment]
My code that combines the final table panics if one of the players who bust on the table that broke leaves before the other table finishes a hand.

I believe that's due to us not recognizing that the player is no longer playing, so we hit this code:
```
            if self.still_playing(*player_id, table_session_id) {
                // We try sending a ClosedConnection, which in turn will try
                // to send a message to the lobby asking to open the table.
                // This is mostly to handle accidental closures.  If people
                // really want to leave the table, they can close the lobby.
```
and `still_playing` returns true, but then when we go to look for the player on the table, the table is gone.

There are a few solutions for this, but my preferred solution is to make sure the player is not considered still playing by the time we bust the table. I need to look into the specifics, because it's been too long since I wrote that code for me to actually remember the nitty gritty.

**Comment by ctm** [comment]
I did some work on this yesterday and didn't add a comment to this issue, but I did write some more code. My final table code still isn't ready, but I did find that the existing code (i.e. w/o my final table additions) will move people in the middle of a hand if someone quits and that leads to a need for fewer tables the next hand. Ugh!

Part of the reason why my final table code didn't work has to do with the same reason why the current code can break tables improperly due to quitting, and it's also something I need to fix to do rebalancing, so I'll incorporate that fix into the branch that has the final table code rather than fixing it separately.

**Comment by ctm** [comment]
I'm deploying my final-table-redraw code now. I still have to add balancing, but that should be fairly easy, although I will probably start tomorrow morning off doing load testing, since that's really the biggest unknown.

**Comment by ctm** [comment]
I added the code that balances tables. I've _very_ lightly tested it locally. I'm deploying it for this evening's game.

**Comment by ctm** [comment]
Ugh. Ran a test tournament and we managed to skip a rank being awarded. I've never seen that before. I suspect a bust player got spirited away to a new table.

I've canceled my deploy and won't merge my current code into master.

There's a chance that the issue is with other work I did today or even a bug that's been there longer. Ugh!

**Comment by ctm** [comment]
This happened as I was trying to recreate the issue:
```
demo127 has joined this table
demo21 has joined this table
demo120 has joined this table
demo126 has joined this table
demo22 has joined this table
demo129 has joined this table

Dealing No-Limit Texas Hold’em (High only)
demo120 antes 100 as the big blind
demo21 blinds 100
demo120 blinds 200
1 B   demo127  30000        0  [  ] [  ]
2     demo21   29900      100  [  ] [  ]
3     demo120  29700 100  200  [  ] [  ]
4   > demo126  30000        0  [  ] [  ]
5     demo22   30000        0  [  ] [  ]
6     demo129  30000        0  [  ] [  ]
                 My cards are: [Qh] [9s]
When it's your time to act, you'll fold
demo126 folds
demo22 folds
demo129 folds
demo127 folds
demo21 folds
Uncalled 100 returned to demo120
demo120  Does Not Show
demo120 wins 300

demo126 was sent to Table 261
Dealing No-Limit Texas Hold’em (High only)
demo22 antes 100 as the big blind
demo120 blinds 100
demo22 blinds 200
1     demo127  30000        0  [  ] [  ]
2 B   demo21   29900        0  [  ] [  ]
3     demo120  30000      100  [  ] [  ]
5     demo22   29700 100  200  [  ] [  ]
6   > demo129  30000        0  [  ] [  ]
                 My cards are: [3h] [9c]
It is 200 to you
demo21 quits in 8th place
demo127 quits in 7th place
demo120 quits in 6th place
demo22 quits in 4th place
Uncalled 100 returned to demo22
No showdown: no pots due to quitters
Pausing to combine to final table...
demo22: who
demo129: who
```

Shortly after I quit demo22, we got a panic:
```
thread '<unnamed>' panicked at 'No first to act, but self.n_live() is 2', mb2/src/table/pot.rs:240:13
```
That panic happened in my test that failed earlier, too. I can try to get some more info.

I think to reproduce this, I start with 12 players, skip the top two popups, quit, skip the next two popups, quit, then go over to the popups for the remaining table and fold all of them, then  just do a bunch of quitting on the table that had the excess player moved from.

I'm going to try doing this without my table motion code, because I"m not convinced it's something I added with that particular set of code.

My suspicion is that this happens whenever we pause to combine the final table with one player left and I just hadn't hit that in testing yet.

**Comment by ctm** [comment]
Could not reproduce it, although I may have missed something. I'm going back to the new code and try to be a little more deterministic and sinplistic.

**Comment by ctm** [comment]
Ugh. I have not been able to reproduce it with the new code after two or three attempts.

I'll have to review the source around the panic.

**Comment by ctm** [comment]
I don't think the panic I've been chasing in the last few comments has to do with table balancing, so I'm closing this ticket.
