### ISSUE TITLE
foreign key violation logging tsid message

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#1001]
Fix the foreign key violation that crashed the tourney earlier today.

```
2022-07-01T22:20:03.086034704Z thread 'main' panicked at 'Error saving tsid message: DatabaseError(ForeignKeyViolation, "insert or update on table \"tsid_messages\" violates foreign key constraint \"tsid_messages_table_session_id_fkey\"")', mb2/src/models.rs:1562:14
2022-07-01T22:20:03.086072365Z stack backtrace:
[...]
2022-07-01T22:20:04.064456164Z   17:     0x55b83d7a6cc6 - mb2::models::TsidMessage::create::h2e48efa2e4fe73e7
2022-07-01T22:20:04.064461474Z                                at /usr/src/poker/mb2/src/models.rs:1559:9
2022-07-01T22:20:04.092641838Z   18:     0x55b83d690af7 - mb2::mb2::nick_mapper::NickMapper::log_tsid_message::h21e0184fbb311647
2022-07-01T22:20:04.092744209Z                                at /usr/src/poker/mb2/src/mb2/nick_mapper.rs:1433:9
2022-07-01T22:20:04.092753339Z   19:     0x55b83d690af7 - mb2::mb2::nick_mapper::NickMapper::tsid_send::h74ee19d38ae775dc
2022-07-01T22:20:04.092757279Z                                at /usr/src/poker/mb2/src/mb2/nick_mapper.rs:1101:17
2022-07-01T22:20:04.099469216Z   20:     0x55b83d6a10ad - <mb2::mb2::nick_mapper::NickMapper as actix::handler::Handler<mb2::mb2::nick_mapper::TableSessionRequest>>::handle::h634d250fcc988156
2022-07-01T22:20:04.099525767Z                                at /usr/src/poker/mb2/src/mb2/nick_mapper.rs:2336:13
```
This is a regression that I introduced when I stopped logging table session ids for observers. The solution is to not call `expect` and instead to call `warn`, perhaps with some backtrace info. That should be done in a few other places too, just because `expect` is ridiculously harsh. I should, however, try to figure out why a non-db `TableSessionId` was in a message to log.

**Comment by ctm** [comment]
I chose to only fix tsid_messages for now. The fix is in master. It will go out with my next deploy.
