### ISSUE TITLE
panic when quitting in certain situations where people are on vacation

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#1005]
Get rid of the panic that we can get if people quit at just the right point.

I ran into this earlier today. I already have a fix, but it's in my `game-spike-944-win-the-button-1003` branch. My fix works, but there's an underlying issue that perhaps should be addressed better.

This is from a build that I never tagged, so the line numbers aren't exact, but the method invocations are:
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', mb2/src/table.rs:5130:13
stack backtrace:
...
  16:        0x107d3ecb3 - <mb2::table::Table as mb2::table::UserActions>::quit::h96f58de8aaf05a2a
                               at /Users/ctm/poker/rust/poker/mb2/src/table.rs:5130:13
  17:        0x107f3a98c - mb2::tournament::RunningEvent::process_user_request::h962123879893d2c6
                               at /Users/ctm/poker/rust/poker/mb2/src/tournament.rs:1796:21
...
```

**Comment by ctm** [comment]
Fixed. Deploying now.
