### ISSUE TITLE
panic in win-the-button

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#1006]
Fix so mb2 won't panic when an uncontested pot is awarded in a win-the-button game.

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', mb2/src/table.rs:2880:46
...
  17:        0x1046de2af - mb2::table::Table::winning_seat::h2855a5adc4d99a2a
                               at /Users/ctm/poker/rust/poker/mb2/src/table.rs:2880:24
  18:        0x1046dcdc0 - mb2::table::Table::showdown::h558892ed17bd00e3
                               at /Users/ctm/poker/rust/poker/mb2/src/table.rs:2745:32
  19:        0x1046e9861 - <mb2::table::Table as mb2::table::NextActions>::award_uncontested::h24cc26edea00bedc
                               at /Users/ctm/poker/rust/poker/mb2/src/table.rs:5043:9
  20:        0x1048df4bc - mb2::tournament::RunningEvent::act::h0e66e2e66b494da5
                               at /Users/ctm/poker/rust/poker/mb2/src/tournament.rs:1031:36
```
I suspect this is a regression and is related to the changes in semantics for vacationed players. Those changes were made a while ago, but win-the-button is played so rarely that I only noticed them as I was testing my `game-spike-944-win-the-button-1003` branch.

Once I can reproduce this, I should be able to fix it easily. The basic problem is that if a pot is awarded uncontested, the `winning_seat` has no pots to look at to determine who won.

**Comment by ctm** [comment]
Fixed in my `game-spike-944-win-the-button-1003` branch.
