### ISSUE TITLE
client panicked during BOOM

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#1008]
Find and fix the bug that caused my client to crash while playing BOOM.

This was soon after I took a re-buy.

This may be a bit hard to track down due to lack of debug symbols.
```
panicked at 'assertion failed: min <= max', /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/cmp.rs:845:9

Stack:

Error
    at Object.Tn (https://devctm.com/235.mb2-web.js:1:18861)
    at __wbg_new_693216e109162396 (https://devctm.com/mb2-web.js:2:4011004)
    at 2874 (https://devctm.com/mb2-web.wasm:wasm-function[3096]:0x21a10a)
    at 1208 (https://devctm.com/mb2-web.wasm:wasm-function[1430]:0x1e0896)
    at 2277 (https://devctm.com/mb2-web.wasm:wasm-function[2499]:0x200903)
    at 2211 (https://devctm.com/mb2-web.wasm:wasm-function[2433]:0x1ff19a)
    at 438 (https://devctm.com/mb2-web.wasm:wasm-function[660]:0x176b2b)
    at 70 (https://devctm.com/mb2-web.wasm:wasm-function[292]:0x942a1)
    at 809 (https://devctm.com/mb2-web.wasm:wasm-function[1031]:0x1c1309)
    at 885 (https://devctm.com/mb2-web.wasm:wasm-function[1107]:0x1cbcde)


En @ 235.mb2-web.js:1
18:08:30.081 /mb2-web.wasm:1 Uncaught RuntimeError: unreachable
    at 1208 (/mb2-web.wasm)
    at 2277 (/mb2-web.wasm)
    at 2211 (/mb2-web.wasm)
    at 438 (/mb2-web.wasm)
    at 70 (/mb2-web.wasm)
    at 809 (/mb2-web.wasm)
    at 885 (/mb2-web.wasm)
    at 173 (/mb2-web.wasm)
    at byn$mgfn-shared$2444 (/mb2-web.wasm)
    at 2447 (/mb2-web.wasm)
```

**Comment by ctm** [comment]
FWIW, this was during Binglaha and I probably timed out, so I should be able to identify the hand by when I got sent to vacation.

**Comment by ctm** [comment]
This is probably a call to `clamp`, which mb2 doesn't directly call that much, so my guess is it's this call:
```
front-ends/web/src/action/graphical.rs
134:                            .clamp(*self.slider_min_value(), *self.slider_max_value())
```
I can imagine that there's a way for min to be greater than max.

**Comment by ctm** [comment]
FWIW, I had rebought on the hand immediately before, so my guess is the two were related. It looks like I was the big blind and I checked until the river. My guess is that my slider values somehow got jacked up due to the rebuy but only got "used" on the river. Perhaps I tried to bet or move the slider or something.

**Comment by ctm** [comment]
It looks very much like `ActionTracker::min_bet` was too high, but I don't see how that can happen at least not if I got the panic where I think I got the panic based on when I was vacationed. Perhaps I got vacationed first due to distraction and the panic came after?

I know it had to happen sometime after I rebought. Perhaps something else is calling `clamp` rather than `clamp_make_n`. This is where a good backtrace would put my mind to rest (contrary to [what I said](https://github.com/ctm/mb2-doc/issues/1010#issuecomment-1175135756) in #1010).
