### ISSUE TITLE
investigate gloo-timers

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#1046]
[See if using `--target web` or `--target no-modules`](https://github.com/rustwasm/gloo/issues/187#issuecomment-1214446719) fixes the [gloo-timers panic](https://github.com/rustwasm/gloo/issues/187).

I'll have to do a little research, since I'm not that familiar with webpack and wasm-bindgen, but at least take a stab at answering @hamza1311's question ASAP.

**Comment by ctm** [comment]
With
```
diff --git a/front-ends/web/webpack.config.js b/front-ends/web/webpack.config.js
index 39f3d356..7867c450 100644
--- a/front-ends/web/webpack.config.js
+++ b/front-ends/web/webpack.config.js
@@ -25,7 +25,7 @@ module.exports = (env, argv) => {
       }),
       new WasmPackPlugin({
         crateDirectory: ".",
-        extraArgs: "--no-typescript",
+          extraArgs: "--no-typescript --target=web",
       })
     ],
       experiments: {
```
I get



```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
    at Module.run_app (index.js:352:14)
    at eval (bootstrap.js:105:12)
```

in the JavaScript console and mb2 doesn't start. When I change `web` to `no-modules` I get a different error message:
```
Uncaught (in promise) TypeError: module.run_app is not a function
    at eval (bootstrap.js:105:12)
```
and mb2 also fails to start.

I'll do a little web searching to see if there's an obvious way I can rewrite `bootstrap.js` to be compatible with either of those targets. Right now the way bootstrap.js gets things started is:
```
import("./pkg").then(module => {
    module.run_app();
});
```

**Comment by ctm** [comment]
[This article](https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm) uses `web` as a target and appears to pull in an init function first. I can't say I understand everything, but at least I have something to futz around with.

**Comment by ctm** [comment]
[Here's](https://rustwasm.github.io/wasm-bindgen/reference/deployment.html) an explanation of the targets.

**Comment by ctm** [comment]
I've summarized my findings and can't think of anything else to do, other than to turn my hack into a PR, perhaps behind a feature flag (e.g., `js-sys-global`).
