### ISSUE TITLE
panic playing TESLA

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#110]
I think this was soon after Frank bust, although I don't know if it was the hand immediately after:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', mb2/src/table.rs:702:9
stack backtrace:
   0:     0x562908a4a7bd - backtrace::backtrace::libunwind::trace::h7b5c372b63026a01
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x562908a4a7bd - backtrace::backtrace::trace_unsynchronized::h653d50182de3f69d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x562908a4a7bd - std::sys_common::backtrace::_print_fmt::h71ae89e108e2b385
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x562908a4a7bd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h838f28d690dfcf3d
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5629088dff8c - core::fmt::write::h828975d842f7a4fc
                               at src/libcore/fmt/mod.rs:1069
   5:     0x562908a49d71 - std::io::Write::write_fmt::h2179c1b9c2a1b6bc
                               at src/libstd/io/mod.rs:1427
   6:     0x562908a498c5 - std::sys_common::backtrace::_print::h2036136edcd87054
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x562908a498c5 - std::sys_common::backtrace::print::h22212fa279a13f4a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x562908a498c5 - std::panicking::default_hook::{{closure}}::h2e60b0f7fb3b6251
                               at src/libstd/panicking.rs:198
   9:     0x562908a48e9c - std::panicking::default_hook::hdef2bfb36d19e1e1
                               at src/libstd/panicking.rs:218
  10:     0x562908a48e9c - std::panicking::rust_panic_with_hook::h68948f866c07f705
                               at src/libstd/panicking.rs:511
  11:     0x562908a48a68 - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x5629088de330 - core::panicking::panic_fmt::h6dc15658acf4542a
                               at src/libcore/panicking.rs:111
  13:     0x5629088de14c - core::panicking::panic::h3bcd263c6b750586
                               at src/libcore/panicking.rs:54
  14:     0x5629089d957c - core::option::Option<T>::unwrap::h721d57612a69dd1b
  15:     0x5629089e1f3b - mb2::table::Table::blind_seat_at::h2bb3d9bc97627117
  16:     0x5629089a43da - mb2::tournament::Tournament::act::h226d050e28a0fdd6
  17:     0x5629089b5d9e - std::sys_common::backtrace::__rust_begin_short_backtrace::hba511021e635a433
  18:     0x5629089d6e68 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h124aa657f0883559
  19:     0x562908a56f4f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hfdb70b1142397bb5
                               at /rustc/1057dc97afce39ff6a224966ece3ed438af4c1f5/src/liballoc/boxed.rs:1017
  20:     0x562908a59173 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h29eb9fb3368b9ea7
                               at /rustc/1057dc97afce39ff6a224966ece3ed438af4c1f5/src/liballoc/boxed.rs:1017
  21:     0x562908a59173 - std::sys_common::thread::start_thread::h1863e5b2662f63bd
                               at src/libstd/sys_common/thread.rs:13
  22:     0x562908a59173 - std::sys::unix::thread::Thread::new::thread_start::h744e397714de2059
                               at src/libstd/sys/unix/thread.rs:80
  23:     0x7f8ec4b226db - start_thread
  24:     0x7f8ec463388f - __clone
  25:                0x0 - <unknown>
```

**Comment by ctm** [comment]
FWIW, we had just played stud for a little while. This was probably the first hand of Lowball. We certainly hadn't played any Lowball previously. My guess is this will be trivial to track down and it's due to someone having bust in a non-blind using game in between blind using games. I'll have to double-check when I set up the blinds, but I think there will be some sort of use of potentially invalid state due to a bust player.

**Comment by ctm** [comment]
Pretty embarrassing, but my code has this comment:
```
                        // TODO: Some code somewhere (perhaps here)
                        // has to deal with players moving into the
                        // table in awkward positions.  However, I
                        // *think* the code we have here is correct if
                        // people aren't moved in, even when one or
                        // more blinds bust.
```
Since I still haven't added multi-table support (#10), I put that comment out of my mind and didn't think about the repercussions when I added support for mixed-game structures. The issue here is that at the end of the hand when I advance the button I also pre-compute which seats will have the blinds. This is done after players have bust, so it worked perfectly fine until I added a mixed game structure where we switch between a game that uses blinds and a game that doesn't and then switches back.

The nice thing is this particular bug is the only known bug that crashes the server and it's in a section of code I was going to revisit "soon" anyway. The other nice thing is that even with a production server build being used, it was still trivial to track this one down.

I'll fix this one and then I'll _probably_ fix (#69) even though it's not strictly in the critical path for unsupervised play-testing. The reason I'll work on #69 afterward is that it's a very good test case for this issue and frankly, the HOE game w/o a fix for #69 is annoying although playable.

**Comment by ctm** [comment]
I'm removing the affected structures:

- hoe_2020
- monte_2019
- pl_horse_2019
- tesla_2019
- toc_2019

I'll then gin up a workaround where if the bug that crashes the server is hit, we'll do something that won't crash the server, but it might result in the wrong person having blinds, then I'll fix it right.

All told, I expect to have the correct fix in sometime tomorrow but should have my little workaround in place for this evenings 7pm Pacific tourney, so we can play MONTE.

**Comment by ctm** [comment]
My comment above about pre-computing the blinds is wrong. Mb2 _doesn't_ pre-compute the blinds when the button moves, which is good, because it really shouldn't. However, that means figuring out exactly what happened is trickier. It also means that a workaround is. little trickier, unless I do something _really_ ugly.

**Comment by ctm** [comment]
It was a lot easier to fix once I looked closely at it. Fixed and deployed.
