### ISSUE TITLE
evaluation failed playing CA Lowball

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#115]
In a TESLA tourney, playing CA lowball, we got this:

```
thread '<unnamed>' panicked at 'found a low ace where one shouldn't be', lib/commands/src/evaluation.rs:136:9
stack backtrace:
  12:     0x5572ad8e28e3 - mb2_commands::evaluation::convert_high_ace_to_low_ace::he3155ede30367733
                               at lib/commands/src/evaluation.rs:136
  13:     0x5572ad8e28e3 - mb2_commands::evaluation::california::California::eval5::h8cced65ee72921cf
                               at lib/commands/src/evaluation/california.rs:40
  14:     0x5572ad8e2aa7 - mb2_commands::evaluation::california::California::eval5_u64::h05cd0e90a0c8a743
                               at lib/commands/src/evaluation/california.rs:0
  15:     0x5572ad8e2af1 - mb2_commands::evaluation::california::California::eval5_u64_no_qualifier::h165cc4a939152ebf
                               at lib/commands/src/evaluation/california.rs:129
  16:     0x5572ad86e284 - mb2::game::best_hand_from::hb4cb60c2640c3cfd
                               at mb2/src/game.rs:200
```

I had the bug and my guess is that a previous fix I made long ago caused the evaluation to fail.

```
GrizzB draws 2
You must discard between 0 and 5 cards
deadhead draws 1
            My cards are: [BG] [Kh] [6s] [2s] [4c]
When it's your time to act, you'll try to call any action
GrizzB checks
deadhead checks
```

**Comment by ctm** [comment]
Off the top of my head, the only two games where we use a bug are CA Lowball and 5-card draw. I'll pull those two games, and any tourney structures that use them, now and deal with this in the morning.

**Comment by ctm** [comment]
Fixed and deployed.
