### ISSUE TITLE
crashes if we have too many entrants

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#138]
Tonight's second crash was due to me having removed some guard code a little while back when I was adding support for breaking a table. mb2 already supports running multiple tables for a tournament, but it doesn't have code to balance or break tables as players bust. As such, I used to have code in place that simply started a tournament when the number of entrants matched the number of seats at a table. I took that code out in anticipation of a [hack-and-slash implementation of busting tables](https://github.com/ctm/mb2-doc/issues/10#issuecomment-611063684), but somehow that removal made it into my `master` branch instead of my `breakdown-10` branch.

`breakdown-10` is close to being ready to be merged, I think, but I won't take any chances and will put in code that disallows starting with too many players.

FTR, here's the relevant backtrace:
```
2020-04-13 00:37:33,191 INFO  [actix_server::builder] Starting "actix-web-service-0.0.0.0:8081" service on 0.0.0.0:8081
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', mb2/src/table.rs:371:38
stack backtrace:
...
  15:     0x5652f73d5001 - mb2::table::Table::new::h9717f4849ba05147
                               at mb2/src/table.rs:371
  16:     0x5652f73d5cb0 - mb2::table::Table::temp_default::hed6efd5442aa8f69
                               at mb2/src/table.rs:588
```

**Comment by ctm** [comment]
Fixed and deployed.
