### ISSUE TITLE
panic (probably vacation related)

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#14]
Yesterday evening, when I was testing 8 players in stud forcing a community card, I got this:
```
    thread '<unnamed>' panicked at 'index out of bounds: the len is 8 but the index is 127', src/table/seat_index.rs:95:22
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:1165:5
```    
But without a backtrace, I don't know where it came from nor do I know how to repeat it.  I doubt it has anything to do with the code I had recently added.

Most likely the value `127` came from `SeatIndex::do_not_use()`. I should never run w/o `RUST_BACKTRACE` set, although I got out of the habit because panics basically just haven't been happening in all my recent testing. However, manually calling from 8 ill-arranged terminal windows was hectic and I probably did something in that rush that I haven't done before.

In addition to running with `RUST_BACKTRACE` set, I've also changed `do_not_use()` to return `126`, so that if I get a panic with the index being `126`, I'll be more certain of the origin of the value. Luckily, since there are only three fields that are initialized with `do_not_use()`, I may be able to figure out what happened by code inspection.

**Comment by ctm** [comment]
It wasn't vacation related. Turns out I never tested an obvious case when I fixed #8. Once I knew where to look, this panic was trivially reproducible and just as trivially fixed.
