### ISSUE TITLE
vacationing on break panics?

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#157]
I'm guessing this is related to vacationing during break, because I added new vacation code to the front-end and people were trying it out. Nancy had a lock-up earlier, so I was trying it repeatedly to see if I could get a lock-up. I think others were trying it just out of curiousity.˘

```
thread '<unnamed>' panicked at 'player PlayerId(55) not in got to do_advanced', mb2/src/table.rs:1572:13
stack backtrace:
...
  13:     0x5622b9522dfc - mb2::table::Table::do_advanced::he2f8d5dffe3b413f
                               at mb2/src/table.rs:1572
  14:     0x5622b9522dfc - mb2::table::Table::player_action::hea62c13c33c40ec3
                               at mb2/src/table.rs:1558
  15:     0x5622b9526b60 - <mb2::table::Table as mb2::table::UserActions>::vacation::h6d72ddf5d9cd162e
                               at mb2/src/table.rs:2440
  16:     0x5622b9558d75 - mb2::tournament::Tournament::process::h1f8eaa7ba5b49163
                               at mb2/src/tournament.rs:537
```

Here's what my table saw:
```
7    [GrizzB]   18600[   0] 
Board: 8c 9c Ah 7d Js
gerdog checks
MeMyself bets 1600
JADC calls
gerdog calls
MeMyself  5c 2d Tc 8d
    High  Jack High Straight   Js Tc 9c 8d 7d
     Low  Eight (8 7 5 2 A)    8c 7d 5c 2d Ah
JADC      Mucks
gerdog    2c 3s Ad 4h
    High  Pair of Aces         Ad Ah Js 9c 4h
     Low  Eight (8 7 3 2 A)    8c 7d 3s 2c Ah
MeMyself  wins  7400 for High
gerdog    wins  7400 for Low

We're now on break
JADC: 3 pair any good?
gerdog: in Pai Gow
JADC: + busted nut flush draw
gerdog has gone on vacation
gerdog is back from vacation
deadhead has gone on vacation
JADC has gone on vacation
gerdog: heh
JADC: test
```

**Comment by ctm** [comment]
FTR, JADC is indeed player 55. My guess is this will be trivial to reproduce and fix.

**Comment by ctm** [comment]
FWIW, it is indeed trivially reproducible, although the obvious trivial fix just lets us get a little further and then we panic for a different reason. It still should be easy to fix, although I won't get to it tonight.

**Comment by ctm** [comment]
Fixed. Deploying now.
