### ISSUE TITLE
bust players were moved to the new table

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#164]
My code that detects when to break a table doesn't take into consideration that you don't need to move any of the other bust players.  That caused this behavior:
```
1   > tombayz      2  9750 2400  [  ] [  ] [  ] [  ] [  ]
2     gerdog       0 12150 2400  [  ] [  ] [  ] [  ] [  ]
3     ghoti        2 20749 2400  [  ] [  ] [  ] [  ] [  ]
4 B   deadhead     2  8713 2400  [  ] [  ] [  ] [  ] [  ]
5    [NNR13]       0  8638[ 400] 
6    [Troutboy]    0  5000[   0] 
7    [GrizzB]      0 95000[   0] 
8    [maverick600] 0     0[   0] 
9    [JADC]        0     0[   0] 
...
Board: 4c 8c 8s 6c 5d
My cards are: [Ts] [8d] [9h] [Ad] [Qc]
tombayz   2d As Ah Ks Qs
    High  Two Pair (Aces and Eights)   Ah As 8s 8c 6c
     Low  Six (6 5 4 2 A)              6c 5d 4c 2d As
ghoti     Jd Ac Qh 4s Jc
    High  Ace High Flush               Ac Jc 8c 6c 4c
     Low  Eight (8 6 5 4 A)            8s 6c 5d 4s Ac
deadhead  Ts 8d 9h Ad Qc
    High  Three Eights                 8c 8d 8s Ad 6c
     Low  Eight (8 6 5 4 A)            8d 6c 5d 4c Ad
  1: tombayz   wins  1037 for Low
  1: ghoti     wins  1037 for High
M  : tombayz   wins 18069 for Low
M  : ghoti     wins 18070 for High

deadhead redeemed a lammer for 5000

maverick600 bust in 7th place
JADC bust in 6th place
```
At that point we still had 7 players left. My guess is that maverick600 and JADC were also counted as having bust on the other table.

I'll see what I can dig out of the database.

Not too surprisingly, once the rank got to 0 or negative, we got a panic:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', mb2/src/table.rs:1374:32
stack backtrace:
  15:     0x56509c2397fc - mb2::table::Table::post_decrement::h4196f8aa871dc0da
                               at mb2/src/table.rs:1374
  16:     0x56509c2397fc - mb2::table::Table::remove_dead_players::hde8da7be51d59807
                               at mb2/src/table.rs:1360
```

I'm pretty sure this is essentially all the same bug. If not, I'll split it into separate issues.

**Comment by ctm** [comment]
Yup, the `public_table_messages` log confirms that jadc and maverick600 were both bust twice. I also see the errant code. It has a trivial fix.

**Comment by ctm** [comment]
Fixed. Deploying now.
