### ISSUE TITLE
Another quitting related panic

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#291]
While testing sit 'n' goes, I got this panic:
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', lib/commands/src/game.rs:234:46
...
  17:        0x101b73bd2 - mb2_commands::game::hands_won::{{closure}}::{{closure}}::hea706637d9bee6b6
                               at lib/commands/src/game.rs:234
...
  26:        0x101b73c53 - mb2_commands::game::hands_won::{{closure}}::h453caa26d291f2ef
                               at lib/commands/src/game.rs:234
...
  35:        0x101b736c1 - mb2_commands::game::hands_won::h73668bb07e50ca2a
                               at lib/commands/src/game.rs:232
  36:        0x101b6a7bd - <mb2_commands::game::hold_em::HoldEm as mb2_commands::game_group::GameGroup>::hand_winnings::h4bae59bfb16725a7
                               at lib/commands/src/game/hold_em.rs:88
  37:        0x101922196 - mb2::table::Table::showdown::h74f92005e3029973
                               at mb2/src/table.rs:1240
  38:        0x101929581 - <mb2::table::Table as mb2::table::NextActions>::award_uncontested::hd02fbdb6e2eddf91
                               at mb2/src/table.rs:2572
  39:        0x10194afef - mb2::tournament::Tournament::act::h1d9f8c33c5939e27
                               at mb2/src/tournament.rs:407
  40:        0x10194a055 - mb2::tournament::Tournament::run::hd4c17963a16f1990
                               at mb2/src/tournament.rs:309
  41:        0x101913fe3 - mb2::tournament::Tournament::start::{{closure}}::h23155f0d575d9c87
                               at mb2/src/tournament.rs:299

```

```
dh5 has joined this table
dh4 has joined this table
dh2 has joined this table
deadhead has joined this table
dh3 has joined this table
dh6 has joined this table

Dealing No-Limit Texas Hold’em (High only)
dh2 antes 100 as the big blind
dh4 blinds 100
dh2 blinds 200
1 B   dh5       30000        0  [  ] [  ]
2     dh4       29900      100  [  ] [  ]
3     dh2       29700 100  200  [  ] [  ]
4   > deadhead  30000        0  [  ] [  ]
5     dh3       30000        0  [  ] [  ]
6     dh6       30000        0  [  ] [  ]
                  My cards are: [2c] [8d]
deadhead raises 29800 to 30000 and is all-in
dh3 calls and is all-in
dh6 calls and is all-in
It is 30000 to you
deadhead quits in 6th place
dh3 quits in 5th place
dh6 quits in 4th place
dh2 quits in 3rd place
dh4 quits in 2nd place
```

I think the problem is simply the all-in status of the quitters. Most likely the code isn't smart enough to realize that there's no need for a showdown in this situation.

I'll double check that I can reproduce this in a normal (i.e., non-sit-n-go) tourney and if so, I'll go ahead and deploy the sit 'n' go code and announce it and then fix this.

**Comment by ctm** [comment]
Indeed, this has nothing to do with sit 'n' goes.

**Comment by ctm** [comment]
Fixed. Too close to this evening's game for me to deploy.
