### ISSUE TITLE
crash due to new player motion code

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#303]
Yesterday's night tournament crashed. It was the second tournament running some new code associated with preventing player motion from causing a player to have the big blind twice. 

There _should_ be enough info in the logs for me to track this down and fix.

```
ubuntu@ip-172-30-0-75:~$ sudo docker logs mb2 2>&1 | grep -v SendError
Running migration 20200707225824
2020-07-08 14:34:59,473 INFO  [mb2] Started 0.0.0.0:8080
2020-07-08 14:34:59,480 INFO  [actix_server::builder] Starting 2 workers
...
Trying to blind folded PlayerId(12)
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', mb2/src/table.rs:1683:34
stack backtrace:
...
  15:     0x558c77114aaf - mb2::table::Table::player_about_to_big_blind_or_random::hb54cea9cd660bedc
                               at mb2/src/table.rs:1683
  16:     0x558c770310b3 - mb2::tournament::Tournament::player_about_to_pay_big_blind::h2d340ce4365734df
                               at mb2/src/tournament.rs:620
  17:     0x558c770310b3 - mb2::tournament::Tournament::move_one_player::h7547b45479275751
                               at mb2/src/tournament.rs:614
  18:     0x558c770310b3 - mb2::tournament::Tournament::table_remains_after_rebalance::h68a75fb2139271b1
```

**Comment by ctm** [comment]
Oh, this turned out to be ridiculously obvious:
```
     pub(crate) fn player_about_to_big_blind_or_random(&mut self) -> Player {
         let index = match self.blind_seats {
             None => self.random_player_holding_seat(),
-            Some(BlindSeats { big_blind_seat, .. }) => big_blind_seat.succ(self.n_seats).into(),
+            Some(BlindSeats { big_blind_seat, .. }) => {
+                self.next_present_seat(big_blind_seat).into()
+            }
         };
         self.seats[index].take().unwrap()
     }
```

I was taking the player at the seat immediately past the big blind, regardless of whether there was a player there. The fix is to use `next_present_seat` which only returns a seat if there is a non-quit player in the seat.

Deploying now.
