### ISSUE TITLE
blind related crash

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#315]
I haven't had a chance to look at this closely, but it appears to be related to the fix I put in that prevents people from getting the blind twice (#290). In theory, this one will be easy to find and fix.

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', mb2/src/table.rs:829:29
stack backtrace:
...
  15:     0x56033c64c858 - mb2::table::Table::mut_player_at::hf85bd30ca38dbe5e
                               at mb2/src/table.rs:829
  16:     0x56033c64c858 - mb2::table::Table::blind_seat_at::h6f978c80ad32db7f
                               at mb2/src/table.rs:856
  17:     0x56033c655918 - mb2::table::Table::blind::hd15e62eae3345b95
                               at mb2/src/table.rs:847
  18:     0x56033c655918 - <mb2::table::Table as mb2::table::NextActions>::begin_hand::h78f47c622ce8c44c
                               at mb2/src/table.rs:2590
```

**Comment by ctm** [comment]
This was the first hand of a game that uses blinds after a stud game (which doesn't). As such, the pre-computed blind info was probably stale.

I believe simple code inspection will tell me what happened, especially since I can query the database to see all the previous action.

**Comment by ctm** [comment]
Fixed. Deploying shortly.
