### ISSUE TITLE
crash! from reconnect?

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#336]
```
2020-07-27 23:35:08,980 INFO  [mb2] Started 0.0.0.0:8080
2020-07-27 23:35:08,987 INFO  [actix_server::builder] Starting 2 workers
2020-07-27 23:35:08,987 INFO  [actix_server::builder] Starting "actix-web-service-0.0.0.0:80" service on 0.0.0.0:80
2020-07-27 23:35:08,987 INFO  [actix_server::builder] Starting "actix-web-service-0.0.0.0:8080" service on 0.0.0.0:8080
2020-07-27 23:35:08,987 INFO  [actix_server::builder] Starting "actix-web-service-0.0.0.0:8081" service on 0.0.0.0:8081
2020-07-27 23:35:08,987 INFO  [actix_server::builder] Starting "actix-web-service-0.0.0.0:443" service on 0.0.0.0:443
thread 'main' panicked at 'no entry found for key', mb2/src/mb2/nick_mapper.rs:349:32
stack backtrace:
  16:     0x561eade9e1bf - mb2::mb2::nick_mapper::NickMapper::tournament_for::h8f6cf2d538b7860a
                               at mb2/src/mb2/nick_mapper.rs:349
  17:     0x561eade9e1bf - mb2::mb2::nick_mapper::NickMapper::send_tournament::h8a7f81ef1bca5b2d
                               at mb2/src/mb2/nick_mapper.rs:898
  18:     0x561eade9e1bf - mb2::mb2::nick_mapper::NickMapper::reconnect::h033ef8b387b60f86
                               at mb2/src/mb2/nick_mapper.rs:885
  19:     0x561eade9e1bf - <mb2::mb2::nick_mapper::NickMapper as actix::handler::Handler<mb2::mb2::nick_mapper::Sit>>::handle::h54e1faee99a82e0a
                               at mb2/src/mb2/nick_mapper.rs:1372
```

**Comment by ctm** [comment]
So, the issue is that reconnect was trying to get info for a tournament that doesn't exist. There are two issues: one is why was it referencing something that doesn't exist? The other is shouldn't it simply ignore such a thing? The answer to the latter is yes. I still need to know the former though.

**Comment by ctm** [comment]
I think it's just a matter of someone reconnecting after a tournament is over.

I have a fix in master that prevents the crash. The client on the other side might get a bad experience, but I'm not going to sweat that yet.
