### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#346]
Last night, during reindeer games:
```
2020-08-02T03:30:00.154564131Z thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', mb2/src/table.rs:833:29
2020-08-02T03:30:00.156118721Z stack backtrace:
2020-08-02T03:30:00.881046167Z   14:     0x55d46692df9d - core::option::Option<T>::unwrap::ha1f0dc1cba8a4946
2020-08-02T03:30:00.881141479Z                                at /rustc/db0492ace429cfeb3567e2c04e300be7df9972ff/library/core/src/option.rs:386
2020-08-02T03:30:00.881152779Z   15:     0x55d46692df9d - mb2::table::Table::mut_player_at::h1d4e835cba9cc8dd
2020-08-02T03:30:00.881177489Z                                at mb2/src/table.rs:833
2020-08-02T03:30:00.881183719Z   16:     0x55d46692df9d - mb2::table::Table::blind_seat_at::hbccc73c4171ff49e
2020-08-02T03:30:00.881188709Z                                at mb2/src/table.rs:862
2020-08-02T03:30:00.881193299Z   17:     0x55d466937451 - mb2::table::Table::blind::h7b38e857111899e8
2020-08-02T03:30:00.881198009Z                                at mb2/src/table.rs:853
2020-08-02T03:30:00.881243290Z   18:     0x55d466937451 - <mb2::table::Table as mb2::table::NextActions>::begin_hand::he140956b61d46916
2020-08-02T03:30:00.881250610Z                                at mb2/src/table.rs:2665
2020-08-02T03:30:00.911062748Z   19:     0x55d46689484d - mb2::tournament::RunningTournament::act::hb2dbc38178903ccb
2020-08-02T03:30:00.911183009Z                                at mb2/src/tournament.rs:421
2020-08-02T03:30:00.911196379Z   20:     0x55d466893c52 - mb2::tournament::RunningTournament::run::h3b3878237a57fa8b
2020-08-02T03:30:00.911202419Z                                at mb2/src/tournament.rs:353
2020-08-02T03:30:00.938389913Z   21:     0x55d466972b66 - mb2::tournament::RunningTournament::start::{{closure}}::h12f15500e9ce25c2
2020-08-02T03:30:00.938459184Z                                at mb2/src/tournament.rs:343
```

I thought I had already addressed this one. I'm moving a little slowly, but this should be easy to track down and fix, although perhaps it'll have to wait until after I ride my bike.

**Comment by ctm** [comment]
FWIW, this was in the Dramaha 3D tournament (event 709, tables 717 & 718).

**Comment by ctm** [comment]
Two people had quit. Others were on vacation.

Obviously quitting shouldn't be able to panic the system, but at least it explains how we could still have a. panicking bug go undetected "so long".

**Comment by ctm** [comment]
Specifically the quitting was done on break. I don't know that the break mattered, but it's worth noting. FWIW, I fond the commit (492c27c143) where I thought I had fixed this bug and it does not address the issue.

**Comment by ctm** [comment]
I've thought of a few ways to fix this. I've asked Chris for advice. I'll do _something_ about it tomorrow if nothing other than disallowing quitting until I figure something better out.

**Comment by ctm** [comment]
I'm going to disallow quitting in the particular circumstance that bites us, which is fairly limited. Specifically, I'll disallow quitting after the button has advanced and before the small blind is paid, if the player who is trying to quit has already been determined to be the small blind.

That's a bit of a hack, but I think it's the right thing to do for now. Other sites implement a more general version of the rule "no quitting".  Obviously, I can implement the "no quitting" rule on top of this rule, should I want.

**Comment by ctm** [comment]
Nope. I've changed my mind. I'm simply going to not have a small blind the next hand. I think that's not only the obvious solution, but the cleanest one and I'm embarrassed that I seriously entertained any others.

**Comment by ctm** [comment]
Fixed. Deploying now.
