### ISSUE TITLE
quitting when all-in on solo ante causes panic

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#353]
Doing some testing involving all-ins I got this panic:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', mb2/src/table.rs:877:29
...
  10:        0x105f00607 - mb2::table::Table::player_at::ha3dae13306941798
                               at mb2/src/table.rs:877
  11:        0x105e4ea8e - mb2::table::Table::showdown::{{closure}}::h1c821de35f7da745
                               at mb2/src/table.rs:1387
```
I'm pretty sure this is just a matter of the code that doesn't allow people to quit if they're in a pot doesn't realize that a solo ante is special cased in a way that it causes it to be overlooked.

The fix is trivial.

**Comment by ctm** [comment]
Fixed. Will go out with the next deploy.
