### ISSUE TITLE
quitting when nobody is left causes a panic

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#354]
With the pausing code, it's possible to get all-in and while the remainder of the board is being dealt have all remaining players quit, even the player who wins due to being the last one to not quit.

When that happens we get:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', mb2/src/table.rs:1632:80
stack backtrace:
...
  10:        0x105f05084 - mb2::table::Table::post_decrement::h9f5c03c5b33f13e4
                               at mb2/src/table.rs:1632
  11:        0x105f05125 - mb2::table::Table::shared_post_decremented::h422e9c950bd2d823
                               at mb2/src/table.rs:1638
  12:        0x105f0b8c4 - <mb2::table::Table as mb2::table::UserActions>::quit::ha9ba1ab608d6bfac
                               at mb2/src/table.rs:2915
```

This is trivial to reproduce and should be trivial to fix.

**Comment by ctm** [comment]
Fixed. Will go out with the next deploy.
