### ISSUE TITLE
panic: demo table didn't go away

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#362]
I just had two demos running simultaneously. One was a five handed MOCK tournament. The other was a two player Oklahoma tournament. I closed the lobby on both but one of the tables remained behind. Turns out it was one of the MOCKs, which isn't too surprising.

Here's what I found in the logs:
```
2020-08-07T18:55:28.665770451Z thread '<unnamed>' panicked at 'player PlayerId(344) not in got to do_advanced', mb2/src/table.rs:1949:13
...
2020-08-07T18:55:29.363782768Z   13:     0x55d007ab6daa - mb2::table::Table::do_advanced::heee1a7f070f9d663
2020-08-07T18:55:29.364194383Z                                at /usr/src/poker/mb2/src/table.rs:1949
2020-08-07T18:55:29.364520947Z   14:     0x55d007ab6daa - mb2::table::Table::player_action::h52c9b8dbd064e889
2020-08-07T18:55:29.364923312Z                                at /usr/src/poker/mb2/src/table.rs:1935
2020-08-07T18:55:29.369136293Z   15:     0x55d007abae4a - <mb2::table::Table as mb2::table::NextActions>::require_action::h5bb2ca29361ef16b
2020-08-07T18:55:29.369149533Z                                at /usr/src/poker/mb2/src/table.rs:2742
2020-08-07T18:55:29.386839045Z   16:     0x55d007bc45ec - mb2::tournament::RunningTournament::act::h88af5983156ac12e
2020-08-07T18:55:29.386939506Z                                at /usr/src/poker/mb2/src/tournament.rs:424
2020-08-07T18:55:29.390926554Z   17:     0x55d007bc3d52 - mb2::tournament::RunningTournament::run::h43bc806d1e6820e8
2020-08-07T18:55:29.390939034Z                                at /usr/src/poker/mb2/src/tournament.rs:353
```

FWIW, I thought I had fixed this with #354, but the code I just added for #358 hit a slightly different edge case.

**Comment by ctm** [comment]
Fixed and deployed.
