### ISSUE TITLE
out of bounds panic

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#47]
mb2 was dead this morning from the following panic:
```
2019-12-11 23:48:20 INFO  [actix_server::builder] Starting 1 workers
2019-12-11 23:48:20 INFO  [actix_server::builder] Starting server on 0.0.0.0:8080
2019-12-11 23:48:20 INFO  [mb2] Started 0.0.0.0:8080
2019-12-11 23:48:20 INFO  [irc::client::conn] Connecting to 172.17.0.3.
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/7dbfb0a8ca4ab74ee3111e57a024f9e6257ce37c/src/libcore/slice/mod.rs:2797:10
stack backtrace:
   0:     0x55eb8463a924 - backtrace::backtrace::libunwind::trace::h0b738e58e75745ca
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55eb8463a924 - backtrace::backtrace::trace_unsynchronized::h8a8fb2cd1b8a2b77
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55eb8463a924 - std::sys_common::backtrace::_print_fmt::h3b7c5cb88cb9285f
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x55eb8463a924 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he931c72117f7927e
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55eb8465d02c - core::fmt::write::hbefb2eecb2cf504f
                               at src/libcore/fmt/mod.rs:1025
   5:     0x55eb84635727 - std::io::Write::write_fmt::he4add739aef71fff
                               at src/libstd/io/mod.rs:1426
   6:     0x55eb8463ca8e - std::sys_common::backtrace::_print::h46691af752cd6693
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55eb8463ca8e - std::sys_common::backtrace::print::h001c0388a605216e
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55eb8463ca8e - std::panicking::default_hook::{{closure}}::h73c204c4c23f8579
                               at src/libstd/panicking.rs:193
   9:     0x55eb8463c781 - std::panicking::default_hook::ha09a3f400c303793
                               at src/libstd/panicking.rs:210
  10:     0x55eb8463d16b - std::panicking::rust_panic_with_hook::hc4e8bece1c2128d1
                               at src/libstd/panicking.rs:471
  11:     0x55eb8463cd1e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x55eb8465915e - core::panicking::panic_fmt::h3f2d4e49be87bb2d
                               at src/libcore/panicking.rs:84
  13:     0x55eb84659125 - core::panicking::panic_bounds_check::hd486102842be1c3e
                               at src/libcore/panicking.rs:62
  14:     0x55eb8432b31d - <mb2::mb2::nick_mapper::NickMapper as actix::handler::Handler<mb2::mb2::nick_mapper::TempProcess>>::handle::h8e534a6bb8e6bfe2
  15:     0x55eb842a9a0c - <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle::hc87623bd86044786
  16:     0x55eb842c8148 - actix::mailbox::Mailbox<A>::poll::h98f7b2a3107344ff
  17:     0x55eb8429db82 - <actix::supervisor::Supervisor<A> as futures::future::Future>::poll::h111269791b03262d
  18:     0x55eb845f7d62 - futures::task_impl::std::set::he8a6105f0f7d0b95
  19:     0x55eb845f24a6 - futures::task_impl::Spawn<T>::poll_future_notify::hed3b11ad6006ed2c
  20:     0x55eb845fdd94 - tokio_current_thread::CurrentRunner::set_spawn::h76280e3f0c638f94
  21:     0x55eb845fd739 - tokio_current_thread::scheduler::Scheduler<U>::tick::h3e988da51331c75c
  22:     0x55eb845fe1ca - tokio_current_thread::Entered<P>::block_on::ha6405247d94d288f
  23:     0x55eb845f4803 - std::thread::local::LocalKey<T>::with::h7c274656a051dd95
  24:     0x55eb845ff747 - tokio_timer::timer::handle::with_default::h1c36e0be2778be6d
  25:     0x55eb845ff7fb - tokio_reactor::with_default::he20313345c0e0660
  26:     0x55eb845ef905 - actix_rt::runtime::Runtime::block_on::hd79b4c21886ff1c8
  27:     0x55eb845ebf13 - actix_rt::builder::SystemRunner::run::h709023af783fa757
  28:     0x55eb842f5ae3 - mb2::main::h2494a0641df90239
  29:     0x55eb8427eb03 - std::rt::lang_start::{{closure}}::hd52bb955ee7089de
  30:     0x55eb8463cbb3 - std::rt::lang_start_internal::{{closure}}::hd26373d679305051
                               at src/libstd/rt.rs:52
  31:     0x55eb8463cbb3 - std::panicking::try::do_call::h43b779197b6d8c8f
                               at src/libstd/panicking.rs:292
  32:     0x55eb846415ba - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  33:     0x55eb8463d6c0 - std::panicking::try::hc0a11e9e690abedb
                               at src/libstd/panicking.rs:270
  34:     0x55eb8463d6c0 - std::panic::catch_unwind::h0ef5ffd7d063b275
                               at src/libstd/panic.rs:394
  35:     0x55eb8463d6c0 - std::rt::lang_start_internal::h54499c9010ea0e45
                               at src/libstd/rt.rs:51
  36:     0x55eb842f5e42 - main
  37:     0x7f3582415b97 - __libc_start_main
  38:     0x55eb842721da - _start
  39:                0x0 - <unknown>
Panic in Arbiter thread.
```

I saw a similar panic last night when doing some live coding at RubiABQ, but later was able to reproduce a different panic, so I mistakenly conflated the two, fixed the new panic and thought I had fixed the original. I was mistaken. Here's the panic I had last night. There are no line numbers, but because it's a debug build we can see that it comes from `TheNickMapper::process`:

```2019-12-11 18:52:10 INFO  [irc::client::conn] Connecting to 127.0.0.1.
Calls from call
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/7dbfb0a8ca4ab74ee3111e57a024f9e6257ce37c/src/libcore/slice/mod.rs:2797:10
stack backtrace:
   0:        0x100e8d585 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h83c7ea93af9711ca
   1:        0x100eae8b0 - core::fmt::write::h14e768261ff6795c
   2:        0x100e885fb - std::io::Write::write_fmt::h847dde63f50fba6e
   3:        0x100e8f8d3 - std::panicking::default_hook::{{closure}}::h074d7a009092a748
   4:        0x100e8f5da - std::panicking::default_hook::h276d9f1716009dcf
   5:        0x100e8ff7b - std::panicking::rust_panic_with_hook::h4a09e69cd55e5140
   6:        0x100e8fb19 - rust_begin_unwind
   7:        0x100ec155c - core::panicking::panic_fmt::h504df364bc4c5c34
   8:        0x100ec1529 - core::panicking::panic_bounds_check::h99962ecf64e8a7ce
   9:        0x1005c5189 - <usize as core::slice::SliceIndex<[T]>>::index::hfd482b9bd2fbf450
  10:        0x1005c5025 - core::slice::<impl core::ops::index::Index<I> for [T]>::index::h062a2209ec50a99a
  11:        0x1005c0efb - <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index::h58c617e90716f688
  12:        0x1003de758 - mb2::mb2::nick_mapper::TheNickMapper::process::h24ae6e27313ed2ba
  13:        0x1003e031a - <mb2::mb2::nick_mapper::NickMapper as actix::handler::Handler<mb2::mb2::nick_mapper::TempProcess>>::handle::heb22c7cdafeee025
```
Currently I don't log enough info for me to be able to trivially track this down, but I may get lucky and be able to figure it out via the process of elimination.

This does point out the need for both more logging as well as something to restart mb2 after a crash, although I will definitely want to add a database before adding restarts and probably before more logging, since we definitely want a db to save state and certainly want a database to save at least some types of logs.

**Comment by ctm** [comment]
Fixed. Deploying now.
