### ISSUE TITLE
Mexican Big Bet Crash

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#477]
`Dealing #113245: 500 1000 No-Limit Mexican (High only)`

```
thread '<unnamed>' panicked at 'attempt to add with overflow', lib/commands/src/types.rs:280:20
stack backtrace:
   0:     0x55c1e13c7070 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55c1e13c7070 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55c1e13c7070 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:     0x55c1e13c7070 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:     0x55c1e13eabcc - core::fmt::write::h9ddafa4860d8adff
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:     0x55c1e13c0ae7 - std::io::Write::write_fmt::h1d2ee292d2b65481
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:     0x55c1e13c9370 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:     0x55c1e13c9370 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:     0x55c1e13c9370 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:     0x55c1e13c90bc - std::panicking::default_hook::he30ad7589e0970f9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:     0x55c1e13c99d3 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:     0x55c1e13c95a9 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
  12:     0x55c1e13c74fc - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
  13:     0x55c1e13c9569 - rust_begin_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
  14:     0x55c1e13e8791 - core::panicking::panic_fmt::h4e2659771ebc78eb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
  15:     0x55c1e13e86dd - core::panicking::panic::h4b079e3c35cc1b09
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:50
  16:     0x55c1e116cab2 - <mb2_commands::types::ChipCount as core::ops::arith::Add>::add::h941783828056042c
                               at /usr/src/poker/lib/commands/src/types.rs:280
  17:     0x55c1e0f84351 - mb2::table::Table::invalid_make::hd7d742ea239aeda8
                               at /usr/src/poker/mb2/src/table.rs:831
  18:     0x55c1e0f84351 - mb2::table::Table::invalid_action::hc830377d761f2928
                               at /usr/src/poker/mb2/src/table.rs:891
  19:     0x55c1e0f84351 - <mb2::table::Table as mb2::table::UserActions>::set_action::he4dd14f6e15dd2b4
                               at /usr/src/poker/mb2/src/table.rs:3457
  20:     0x55c1e0f5dddc - mb2::tournament::RunningTournament::process::hb6613228c2528d6a
                               at /usr/src/poker/mb2/src/tournament.rs:1111
  21:     0x55c1e0f59598 - mb2::tournament::RunningTournament::run::hf4cdac12ddb53836
                               at /usr/src/poker/mb2/src/tournament.rs:471
  22:     0x55c1e10a6e74 - mb2::tournament::RunningTournament::start::{{closure}}::h4c247a6fe6ab2e6a
                               at /usr/src/poker/mb2/src/tournament.rs:439
  23:     0x55c1e10a6e74 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4dfaebe1f6f3bd7a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:137
  24:     0x55c1e10a76b5 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h905612cd9e42361f
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/mod.rs:458
  25:     0x55c1e10a76b5 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h290b82dea2c8fa75
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:308
  26:     0x55c1e10a76b5 - std::panicking::try::do_call::h7b61f162115df0d9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
  27:     0x55c1e10a76b5 - std::panicking::try::ha3fc528817f2559c
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
  28:     0x55c1e10a76b5 - std::panic::catch_unwind::hcf93ce5539befe50
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
  29:     0x55c1e10a76b5 - std::thread::Builder::spawn_unchecked::{{closure}}::h956b0bdacaf40b16
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/mod.rs:457
  30:     0x55c1e10a76b5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h985df55fa3f29628
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
  31:     0x55c1e13cdf5a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h670c50864ac2cb92
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
  32:     0x55c1e13cdf5a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2511952749086d81
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
  33:     0x55c1e13cdf5a - std::sys::unix::thread::Thread::new::thread_start::h5ad4ddffe24373a8
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/unix/thread.rs:87
  34:     0x7ff9f5aef609 - start_thread
  35:     0x7ff9f59f9293 - clone
  36:                0x0 - <unknown>
```

**Comment by ctm** [comment]
This crash comes from overflow associated with the make command. The cause of the overflow being the same problem that was causing bad things to happen with the default raise button in #474). However, there's a subtle issue in that any time we do addition with user generated input, we'll have to use a checked add rather than a stock add, because a user could deliberately type a number that is small enough to parse properly but large enough to cause overflow.

So, although fixing #474 should prevent this from happening again accidentally, I can't close this ticket until I address the issue of deliberately crafted large numbers in make or raise boxes (and I'll have to double-check the call box, but I don't think there's addition involved with it).

**Comment by ctm** [comment]
Fixed in master. It'll go out with the next deploy.
