### ISSUE TITLE
Ring Game resulted in Crash

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#563]
Earlier this afternoon, Grizz and I played a ring game. Afterward there was a crash that was related.

As best I remember (and I can look at the logs to be sure), he and I played, each w/100 starting chips. He bust, then quit and later came back with IIRC, 1000 chips. We played a little longer and then I quit. He appeared not to quit, although I can't be sure whether he tried or not.

Later, when the evening game was running, I tried to rejoin the table, but when I clicked on the blue link in the lobby I was never seated. I did a `sudo docker logs mb2` and didn't see anything suspicious. I did, however, have my internet drop. After that, I closed my lobby and got back into the evening tournament and was playing for a while when the tourney locked up. After that I asked for logs and got this handful:

```
2021-03-27 11:23:46,225 INFO  [mb2] Started 0.0.0.0:8080
2021-03-27 11:23:46,230 INFO  [actix_server::builder] Starting 2 workers
2021-03-27 11:23:46,231 INFO  [actix_server::builder] Starting "actix-web-service-0.0.0.0:80" service on 0.0.0.0:80
2021-03-27 11:23:46,231 INFO  [actix_server::builder] Starting "actix-web-service-0.0.0.0:8080" service on 0.0.0.0:8080
2021-03-27 11:23:46,231 INFO  [actix_server::builder] Starting "actix-web-service-0.0.0.0:8081" service on 0.0.0.0:8081
2021-03-27 11:23:46,231 INFO  [actix_server::builder] Starting "actix-web-service-0.0.0.0:443" service on 0.0.0.0:443
messages: []
2021-03-29 00:07:13,217 WARN  [mb2::mb2::nick_mapper] player_observe: TableNotRunning
2021-03-29 00:07:58,997 WARN  [mb2::mb2::nick_mapper] player_observe: TableNotRunning
2021-03-29 00:08:36,051 WARN  [mb2::mb2::nick_mapper] player_observe: TableNotRunning
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', mb2/src/mb2/nick_mapper.rs:1424:58
stack backtrace:
   0:     0x5611a3946070 - std::backtrace_rs::backtrace::libunwind::trace::h25e12e0d899beba0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5611a3946070 - std::backtrace_rs::backtrace::trace_unsynchronized::h70e61195d6ae3df6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5611a3946070 - std::sys_common::backtrace::_print_fmt::hba93ab80d779695a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5611a3946070 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf092b5883b4b2e50
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5611a396778c - core::fmt::write::hf68bc350a8f2f0dc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:     0x5611a393f062 - std::io::Write::write_fmt::hf66811b1bc767436
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:     0x5611a39481d5 - std::sys_common::backtrace::_print::hd425a11bfe1f20f8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5611a39481d5 - std::sys_common::backtrace::print::h6d678795c1e61e13
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5611a39481d5 - std::panicking::default_hook::{{closure}}::h78a02a4a0dee5e7e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:     0x5611a3947d2a - std::panicking::default_hook::h56eb7eda02f355a7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:     0x5611a3948971 - std::panicking::rust_panic_with_hook::hb27ea14285131c61
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:     0x5611a3948487 - std::panicking::begin_panic_handler::{{closure}}::hc552fcee62aad17f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:495:13
  12:     0x5611a394652c - std::sys_common::backtrace::__rust_end_short_backtrace::hb9f0aa9a78e885a0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5611a3948419 - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:     0x5611a3965471 - core::panicking::panic_fmt::h12ac4570ea43d06f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  15:     0x5611a39653bd - core::panicking::panic::h72bd72f6f4a70105
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
  16:     0x5611a35200e5 - core::option::Option<T>::unwrap::hd504a064d00ad719
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:386:21
  17:     0x5611a35200e5 - mb2::mb2::nick_mapper::NickMapper::left_ring_game::h0a93f1da58cde9e9
                               at /usr/src/poker/mb2/src/mb2/nick_mapper.rs:1424:24
  18:     0x5611a35200e5 - <mb2::mb2::nick_mapper::NickMapper as actix::handler::Handler<mb2::mb2::nick_mapper::messages::ToTablePublic>>::handle::hc615747a45b8172d
                               at /usr/src/poker/mb2/src/mb2/nick_mapper.rs:1964:17
  19:     0x5611a342e1fc - <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle::he289e1ca80f34e1d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.10.0/src/address/envelope.rs:112:23
  20:     0x5611a3333f89 - <actix::address::envelope::Envelope<A> as actix::address::envelope::EnvelopeProxy>::handle::hab26089264beec05
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.10.0/src/address/envelope.rs:71:9
  21:     0x5611a3333f89 - actix::mailbox::Mailbox<A>::poll::hc2b79e2b904f6b1e
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.10.0/src/mailbox.rs:101:25
  22:     0x5611a3347db3 - <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll::hec901c6b41b3870d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.10.0/src/contextimpl.rs:375:13
  23:     0x5611a3386b69 - <actix::supervisor::Supervisor<A> as core::future::future::Future>::poll::h230a725830ea938f
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.10.0/src/supervisor.rs:151:19
  24:     0x5611a331cfea - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h999521f9096597ad
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
  25:     0x5611a331cfea - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h5d08cc3af1706c44
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  26:     0x5611a331cfea - tokio::runtime::task::core::Core<T,S>::poll::h77eb475241d4b8c9
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
  27:     0x5611a331cfea - tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}::h30eef21086dfc3a7
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  28:     0x5611a331cfea - core::ops::function::FnOnce::call_once::h7fcfd7d5598d046f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
  29:     0x5611a331cfea - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb6029c79840df664
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:322:9
  30:     0x5611a33fa36f - std::panicking::try::do_call::h58d0759a3a642906
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
  31:     0x5611a33fa36f - std::panicking::try::h384d2663ff01b56e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
  32:     0x5611a33fa36f - std::panic::catch_unwind::h5e96a6162af3adf3
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
  33:     0x5611a33fa36f - tokio::runtime::task::harness::Harness<T,S>::poll::ha3c4db254e7bcbdc
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  34:     0x5611a38dea72 - tokio::runtime::task::raw::RawTask::poll::h77b5fd55327abbe4
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  35:     0x5611a38dea72 - tokio::runtime::task::Notified<S>::run::hce579456a3919fc0
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  36:     0x5611a38dea72 - tokio::task::local::LocalSet::tick::{{closure}}::hbbb4b09ba5e97f44
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:408:54
  37:     0x5611a38dea72 - tokio::coop::with_budget::{{closure}}::h46e1b83695761e67
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
  38:     0x5611a38dea72 - std::thread::local::LocalKey<T>::try_with::h98d1738baa674884
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/thread/local.rs:272:16
  39:     0x5611a38dea72 - std::thread::local::LocalKey<T>::with::hae263c6af4733639
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/thread/local.rs:248:9
  40:     0x5611a38e2f17 - tokio::coop::with_budget::h2f29f5819e59de4f
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
  41:     0x5611a38e2f17 - tokio::coop::budget::hbd947fa37bb38da7
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
  42:     0x5611a38e2f17 - tokio::task::local::LocalSet::tick::h2919085f854e7861
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:408:31
  43:     0x5611a339eb2e - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::h69e8c1222f4d37da
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:532:16
  44:     0x5611a339eb2e - tokio::macros::scoped_tls::ScopedKey<T>::set::hc07954ad49bb20e9
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  45:     0x5611a333755b - tokio::task::local::LocalSet::with::h613b2277297a42c4
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:442:9
  46:     0x5611a333755b - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h8e16d0ed57309b31
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:518:9
  47:     0x5611a333755b - tokio::task::local::LocalSet::run_until::{{closure}}::hb0e6919a08cd0c57
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:392:9
  48:     0x5611a333755b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7cb752347665f254
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/future/mod.rs:80:19
  49:     0x5611a339df1f - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}::h541394f7a11a2109
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:131:58
  50:     0x5611a339df1f - tokio::coop::with_budget::{{closure}}::h40ca413b53685654
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
  51:     0x5611a339df1f - std::thread::local::LocalKey<T>::try_with::h1e9b0492d8876ce9
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/thread/local.rs:272:16
  52:     0x5611a339df1f - std::thread::local::LocalKey<T>::with::h6786ac1be8384ad3
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/thread/local.rs:248:9
  53:     0x5611a339df1f - tokio::coop::with_budget::hdf33d6d83376e61c
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
  54:     0x5611a339df1f - tokio::coop::budget::hd2c387caaa3dd387
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
  55:     0x5611a339df1f - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::h543579b93315463b
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:131:35
  56:     0x5611a339df1f - tokio::runtime::basic_scheduler::enter::{{closure}}::h513a835678a59d68
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:213:29
  57:     0x5611a339df1f - tokio::macros::scoped_tls::ScopedKey<T>::set::h8ccdc6f66144ccc1
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  58:     0x5611a33465a4 - tokio::runtime::basic_scheduler::enter::h0af3b3543c9cb530
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:213:5
  59:     0x5611a33465a4 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::he174ae4fa9c63ae8
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:123:9
  60:     0x5611a33e52e1 - tokio::runtime::Runtime::block_on::{{closure}}::h774a7b08676fc281
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/mod.rs:444:34
  61:     0x5611a33e52e1 - tokio::runtime::context::enter::had22f64ffcda762f
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
  62:     0x5611a338350e - tokio::runtime::handle::Handle::enter::h45e66fb56e098a13
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
  63:     0x5611a33c13ea - tokio::runtime::Runtime::block_on::h6e8ebe3c5b799d52
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/mod.rs:441:9
  64:     0x5611a33c13ea - tokio::task::local::LocalSet::block_on::hb5a97bc6b990b2d6
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:353:9
  65:     0x5611a33c13ea - actix_rt::runtime::Runtime::block_on::hfc2579196eebfeda
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89:9
  66:     0x5611a33c13ea - actix_rt::builder::SystemRunner::block_on::hd20bd81d1771d7a4
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/builder.rs:187:19
  67:     0x5611a33e88c2 - mb2::main::h559879f59ddae4d7
                               at /usr/src/poker/mb2/src/main.rs:261:1
  68:     0x5611a33b4003 - core::ops::function::FnOnce::call_once::h067acdaf11019206
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
  69:     0x5611a33b4003 - std::sys_common::backtrace::__rust_begin_short_backtrace::hab947f6555b40420
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:125:18
  70:     0x5611a33b4019 - std::rt::lang_start::{{closure}}::h8cbb914504f812f5
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:66:18
  71:     0x5611a3948e87 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h78040f802d89ccdc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:259:13
  72:     0x5611a3948e87 - std::panicking::try::do_call::h6853cad536dd09a1
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
  73:     0x5611a3948e87 - std::panicking::try::h827495f03a9fbb9a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
  74:     0x5611a3948e87 - std::panic::catch_unwind::h4bdf17571090eb17
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
  75:     0x5611a3948e87 - std::rt::lang_start_internal::h2f319c33bb013f29
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:51:25
  76:     0x5611a33e8948 - main
  77:     0x7ff4995190b3 - __libc_start_main
  78:     0x5611a324915a - _start
  79:                0x0 - <unknown>
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
2021-03-29 00:13:49,250 ERROR [mb2::tournament] recv(user_input) failed: receiving on an empty and disconnected channel
thread '<unnamed>' panicked at 'too many errors', mb2/src/tournament.rs:1571:13
stack backtrace:
   0:     0x5611a3946070 - std::backtrace_rs::backtrace::libunwind::trace::h25e12e0d899beba0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5611a3946070 - std::backtrace_rs::backtrace::trace_unsynchronized::h70e61195d6ae3df6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5611a3946070 - std::sys_common::backtrace::_print_fmt::hba93ab80d779695a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5611a3946070 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf092b5883b4b2e50
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5611a396778c - core::fmt::write::hf68bc350a8f2f0dc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:     0x5611a393f062 - std::io::Write::write_fmt::hf66811b1bc767436
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:     0x5611a39481d5 - std::sys_common::backtrace::_print::hd425a11bfe1f20f8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5611a39481d5 - std::sys_common::backtrace::print::h6d678795c1e61e13
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5611a39481d5 - std::panicking::default_hook::{{closure}}::h78a02a4a0dee5e7e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:     0x5611a3947d2a - std::panicking::default_hook::h56eb7eda02f355a7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:     0x5611a3948971 - std::panicking::rust_panic_with_hook::hb27ea14285131c61
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:     0x5611a35710f4 - std::panicking::begin_panic::{{closure}}::hafd344990c01cf7a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:520:9
  12:     0x5611a357105c - std::sys_common::backtrace::__rust_end_short_backtrace::h5faa00c7f03cf74c
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5611a34b4adc - std::panicking::begin_panic::ha13f58c725376314
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:519:12
  14:     0x5611a349fbc1 - mb2::tournament::RunningEvent::increase_error_count::he1157c4b1c1d15eb
                               at /usr/src/poker/mb2/src/tournament.rs:1571:13
  15:     0x5611a349fbc1 - mb2::tournament::RunningEvent::run::ha0a10c2bc6c94a32
                               at /usr/src/poker/mb2/src/tournament.rs:588:33
  16:     0x5611a3571086 - mb2::tournament::RunningEvent::start::{{closure}}::ha7a69ad01a851542
                               at /usr/src/poker/mb2/src/tournament.rs:547:31
  17:     0x5611a3571086 - std::sys_common::backtrace::__rust_begin_short_backtrace::h267d6e33a770bfaa
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:125:18
  18:     0x5611a34b4ead - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h1fc9b8760bbc071c
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/thread/mod.rs:474:17
  19:     0x5611a34b4ead - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6a86449bcb9080be
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:322:9
  20:     0x5611a34b4ead - std::panicking::try::do_call::h3a1b9947e6edf2b7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
  21:     0x5611a34b4ead - std::panicking::try::h943db395d0a761e0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
  22:     0x5611a34b4ead - std::panic::catch_unwind::h92020bbbb655fd24
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
  23:     0x5611a34b4ead - std::thread::Builder::spawn_unchecked::{{closure}}::h3a0a5197082e571a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/thread/mod.rs:473:30
  24:     0x5611a34b4ead - core::ops::function::FnOnce::call_once{{vtable.shim}}::he560c5d91072cd4a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
  25:     0x5611a394d2fa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9ed215ba67984d70
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9
  26:     0x5611a394d2fa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcece06e1fe04906f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/boxed.rs:1328:9
  27:     0x5611a394d2fa - std::sys::unix::thread::Thread::new::thread_start::h6e82a4b7be15319a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys/unix/thread.rs:71:17
  28:     0x7ff499844609 - start_thread
  29:     0x7ff499614293 - clone
  30:                0x0 - <unknown>
2021-03-29 00:14:41,454 WARN  [mb2::mb2::nick_mapper] rpc failed: MailboxError(Mailbox has closed)
```

(I'll edit out a bunch of fluff tomorrow)

I'm marking this as `easy`, because my guess is the logs will point out more than one error to fix that will prevent this from happening again, although to be safe, I'll disable ring games entirely (#562) until I have time to work on them again (which should be fairly soon).

**Comment by ctm** [comment]
So, there are two issues. One I [mention](https://github.com/ctm/mb2-doc/issues/337#issuecomment-809304781) in (#337), but the underlying one is how did the ring game disappear from NickMapper's `tables` `HashMap` while still allowing the code path that brought us to the `left_ring_game` call and that's not obvious, however, `left_ring_game` can be trivially changed to clean up even inconsistent data structures, so I'll do that later today although I still want to see if I can figure out how they got inconsistent because there could be trouble lurking elsewhere.

**Comment by ctm** [comment]
I have not been able to figure out how the data structures got into an inconsistent state, but since I got rid of the blind unwrapping and [], I think it's safe to re-enable ring games.

Deploying now.
