### ISSUE TITLE
unattended demo panics

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#618]
In some cases when the demo is left running it panics.

I don't know the exact details, because in the few times that this has happened I had been working on something and then forgot to stop the demo and then got the panic.

It looks like it happens when two players get on vacation at once, which is&mdash;in theory&mdash;impossible.

```
thread '<unnamed>' panicked at 'No first to act, but self.n_live() is 0, id: 1691, seats: [Some(Player { id: PlayerId(1000063), alt_id: None, chips: ChipCount(42800), lammers: None, action: ChipCount(12000), this_round_action: ChipCount(12000), status: Folded, on_vacation: true, reveal_default: MuckIfBeat, cards: VecOfCards { cards: [] }, advanced_action: None, reveal: None, action_number: 1, discard: None, wants_rebuy: false, rebuy_on_bust: true, lammers_to_redeem: 0, chips_at_start_of_hand: ChipCount(54800), reveal_due_to_all_in: false, checked: false, forfeited_action: ChipCount(0), primary_id: PlayerId(1000063), primary_game: None, has_ever_acted: false }), Some(Player { id: PlayerId(1000062), alt_id: None, chips: ChipCount(9200), lammers: None, action: ChipCount(12000), this_round_action: ChipCount(21200), status: Folded, on_vacation: true, reveal_default: MuckIfBeat, cards: VecOfCards { cards: [] }, advanced_action: None, reveal: None, action_number: 1, discard: None, wants_rebuy: false, rebuy_on_bust: true, lammers_to_redeem: 0, chips_at_start_of_hand: ChipCount(45200), reveal_due_to_all_in: false, checked: false, forfeited_action: ChipCount(0), primary_id: PlayerId(1000062), primary_game: None, has_ever_acted: false }), None, None, None, None, None, None, None]', mb2/src/table/pot.rs:504:13
stack backtrace:
...
  15:        0x109ca1cc9 - <mb2::table::Table as mb2::table::pot::TablePots>::actions::h170bb6c28e42bfb8
                               at /Users/ctm/poker/rust/poker/mb2/src/table/pot.rs:504:13
  16:        0x109ca0e11 - <mb2::table::Table as mb2::table::pot::TablePots>::pots::h4fb8cba77cc9e5fc
                               at /Users/ctm/poker/rust/poker/mb2/src/table/pot.rs:416:23
  17:        0x109cae295 - mb2::table::Table::showdown::he29cf95cc475a252
                               at /Users/ctm/poker/rust/poker/mb2/src/table.rs:1842:24
  18:        0x109cbbba1 - <mb2::table::Table as mb2::table::NextActions>::award_uncontested::h78fe8913add84743
                               at /Users/ctm/poker/rust/poker/mb2/src/table.rs:3774:9
  19:        0x109d78c89 - mb2::tournament::RunningEvent::act::h5a50ea56873a27ae
                               at /Users/ctm/poker/rust/poker/mb2/src/tournament.rs:700:36
  20:        0x109d77a69 - mb2::tournament::RunningEvent::run::he174a3a47be9ea51
                               at /Users/ctm/poker/rust/poker/mb2/src/tournament.rs:576:20
  21:        0x109d7789b - mb2::tournament::RunningEvent::start::{{closure}}::had219b0191c950c0
                               at /Users/ctm/poker/rust/poker/mb2/src/tournament.rs:547:31
```

**Comment by ctm** [comment]
There's a tiny chance that this only happens when time-to-act is cranked up. Earlier when I was testing I often entered 999 in the box when I created the demo. I think the actual max is 180, but that's well above what we normally use and might be more than the amount of time that the demo uses for a break.

**Comment by ctm** [comment]
On the other laptop I tried using the default no-limit demo but with secs-to-act set to 999 (i.e., 180) and with two players I didn't get the panic.  I suspect I had more players when I was getting the panic, although I probably also wasn't playing the default no-limit, so ... I'll want to update that ticket.  In the meantime, I'll fire up a no-limit demo with 5 players and 999.

5 players & 999 got into level 9, well past the break.  Ugh!  

I will have to look at the date and time that I submitted the issue and then go back and look in the local database to see what parameters I started with.  I also may need to look at the activities for the demo players, since it was happening when I was testing, so I doubt that I was firing it up and letting it run completely untouched.

**Comment by ctm** [comment]
I found and fixed this a couple days ago. I was offline and forgot to close this issue at the time.
