### ISSUE TITLE
SoHe panicked (vacation related)

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#626]
```
2021-06-18T03:26:25.166917606Z thread '<unnamed>' panicked at 'discard_draw_or_expose called when setting', mb2/src/table.rs:2763:20
2021-06-18T03:26:25.882769812Z   14:     0x55656da7de95 - mb2::table::Table::discard_draw_or_expose::hee1a10b6e3650d47
2021-06-18T03:26:25.882785863Z                                at /usr/src/poker/mb2/src/table.rs:2763:20
2021-06-18T03:26:25.888724873Z   15:     0x55656da7ced7 - mb2::table::Table::do_vacation::ha6ed4653f8b6a635
2021-06-18T03:26:25.888783533Z   16:     0x55656da7ced7 - mb2::table::Table::player_action::hedc638a2a12d25c2
```

I know what this is. When a player is on vacation and is supposed to do something, the vacation code does something for the player. Before I introduced SoHe, the only two somethings are bet related or discard related, so there's code that says if a player is on vacation and needs to do something that's not bet related, discard or draw the minimum number of cards necessary. The code needs to be told that if the player is on vacation when it's time to set, just take the cards in the order they're already there.

I can fix this super quickly tomorrow morning.

**Comment by ctm** [comment]
Fixed. I can deploy when the server isn't in use.

**Comment by ctm** [comment]
deployed
