### ISSUE TITLE
underflow when decreasing n_not_all_in

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#693]
JADC:
> In Paradise Pick em, Cory all in for less than BB I expose and raise. 
> He said he exposed but we didn't see card. he couldn't do anything and game froze. Hand # 214178

```
2021-09-10T22:27:19.106007768Z messages: []
2021-09-11T03:48:53.739279597Z thread '<unnamed>' panicked at 'attempt to subtract with overflow', mb2/src/table.rs:3664:13
2021-09-11T03:48:53.739861074Z stack backtrace:
2021-09-11T03:48:54.287260878Z   16:     0x557f87e9e7e0 - mb2::table::Table::call::hd7a9b609a4b1afa2
2021-09-11T03:48:54.287276058Z                                at /usr/src/poker/mb2/src/table.rs:3664:13
2021-09-11T03:48:54.290570627Z   17:     0x557f87e9b763 - mb2::table::Table::do_action::hf1c5e2dc22bdb13d
2021-09-11T03:48:54.290583097Z                                at /usr/src/poker/mb2/src/table.rs:2996:35
2021-09-11T03:48:54.292141186Z   18:     0x557f87e9b34d - mb2::table::Table::do_draw_and_action::h3837397b8decdf88
2021-09-11T03:48:54.292154556Z                                at /usr/src/poker/mb2/src/table.rs:3116:28
2021-09-11T03:48:54.292159536Z   19:     0x557f87e9b34d - mb2::table::Table::do_advanced::h2b1e8f44cf31fccc
2021-09-11T03:48:54.292164306Z                                at /usr/src/poker/mb2/src/table.rs:3027:13
2021-09-11T03:48:54.292168776Z   20:     0x557f87e9b34d - mb2::table::Table::player_action::hf9e273aa39f7f0d5
2021-09-11T03:48:54.292173426Z                                at /usr/src/poker/mb2/src/table.rs:2943:23
2021-09-11T03:48:54.292366578Z   21:     0x557f87ea2e23 - <mb2::table::Table as mb2::table::UserActions>::set_action::h8ee2cb503b74cace
2021-09-11T03:48:54.292385329Z                                at /usr/src/poker/mb2/src/table.rs:4525:21
2021-09-11T03:48:54.318316130Z   22:     0x557f87d5ec29 - mb2::tournament::RunningEvent::process_user_request::h1949411501c7d7d9
2021-09-11T03:48:54.318342220Z                                at /usr/src/poker/mb2/src/tournament.rs:1550:34
2021-09-11T03:48:54.318349420Z   23:     0x557f87d5ec29 - mb2::tournament::RunningEvent::process::h7e329f38c9ae1d2d
2021-09-11T03:48:54.318355200Z                                at /usr/src/poker/mb2/src/tournament.rs:1479:37
2021-09-11T03:48:54.320846190Z   24:     0x557f87d57901 - mb2::tournament::RunningEvent::run::hb00eef5001ace46f
2021-09-11T03:48:54.320972712Z                                at /usr/src/poker/mb2/src/tournament.rs:656:49
2021-09-11T03:48:54.332337928Z   25:     0x557f87f17f04 - mb2::tournament::RunningEvent::start::{{closure}}::h6cd961310ca8719f
2021-09-11T03:48:54.332352828Z                                at /usr/src/poker/mb2/src/tournament.rs:618:31
```

**Comment by ctm** [comment]
I've reproduced this locally. One part of the code didn't know LingCod was all-in, so it tried to mark him all-in again. I've got to take a breakfast break, but this should be trivial to fix.

**Comment by ctm** [comment]
Fixed. Deploying now.
