### ISSUE TITLE
panic playing CHEER

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#711]
```
JADC🚴 was busted by gerdog in 5th place
gerdog: gg
deadhead: gg
tegwin: gg
JADC🚴: gg
Dealing #218956: 4000 8000 Four Card Chowaha (High/Low Eight Qualifier)

tegwin blinds 2000
deadhead blinds 4000
2     tegwin      16610 2000  [  ] [  ] [  ] [  ]
3     deadhead    1970 4000  [  ] [  ] [  ] [  ]
4   > gerdog      67170    0  [  ] [  ] [  ] [  ]
6     pokerchimp  28250    0  [  ] [  ] [  ] [  ]
                My cards are: [7d] [6s] [Ac] [Ts]
gerdog folds
pokerchimp folds
tegwin calls
It is 0 to you
```
```
2021-10-05T01:02:49.664893751Z thread '<unnamed>' panicked at 'attempt to subtract with overflow', lib/commands/src/types.rs:316:20
2021-10-05T01:02:49.665388088Z stack backtrace:
...
2021-10-05T01:02:50.368043568Z   16:     0x5600042c3771 - <mb2_commands::types::ChipCount as core::ops::arith::Sub>::sub::h444ef7dcca5dffb8
2021-10-05T01:02:50.368058239Z                                at /usr/src/poker/lib/commands/src/types.rs:316:20
2021-10-05T01:02:50.389348749Z   17:     0x5600041ccfbf - mb2::table::Table::make::h1309a230a6a5a083
2021-10-05T01:02:50.389365099Z                                at /usr/src/poker/mb2/src/table.rs:3775:33
2021-10-05T01:02:50.389370459Z   18:     0x5600041ccfbf - mb2::table::Table::do_action::h2faaded43e4e8f83
2021-10-05T01:02:50.389375159Z                                at /usr/src/poker/mb2/src/table.rs:3057:35
2021-10-05T01:02:50.393269068Z   19:     0x5600041cc01f - mb2::table::Table::do_advanced::h83c3d29c80711bc7
2021-10-05T01:02:50.393283639Z                                at /usr/src/poker/mb2/src/table.rs:3092:13
2021-10-05T01:02:50.393400410Z   20:     0x5600041cc01f - mb2::table::Table::player_action::h657ae7d8acf610f4
2021-10-05T01:02:50.393412030Z                                at /usr/src/poker/mb2/src/table.rs:3001:23
2021-10-05T01:02:50.393601753Z   21:     0x5600041d44ab - <mb2::table::Table as mb2::table::UserActions>::set_action::h9d5888149c7fa06f
2021-10-05T01:02:50.393633953Z                                at /usr/src/poker/mb2/src/table.rs:4638:21
2021-10-05T01:02:50.420001707Z   22:     0x5600042885f9 - mb2::tournament::RunningEvent::process_user_request::h5b2b7d9454c08f22
2021-10-05T01:02:50.420032607Z                                at /usr/src/poker/mb2/src/tournament.rs:1557:34
2021-10-05T01:02:50.420038227Z   23:     0x5600042885f9 - mb2::tournament::RunningEvent::process::hcf818a17b9cab29b
2021-10-05T01:02:50.420042837Z                                at /usr/src/poker/mb2/src/tournament.rs:1486:37
2021-10-05T01:02:50.427938668Z   24:     0x560004281231 - mb2::tournament::RunningEvent::run::hd7cad860df40f204
2021-10-05T01:02:50.427952988Z                                at /usr/src/poker/mb2/src/tournament.rs:655:49
2021-10-05T01:02:50.438387540Z   25:     0x560004071ec4 - mb2::tournament::RunningEvent::start::{{closure}}::h6c6e049ac894e1bb
2021-10-05T01:02:50.438413600Z                                at /usr/src/poker/mb2/src/tournament.rs:617:31

**Comment by ctm** [comment]
Ugh. The death is in ancient code and should be trivially fixable. I should have it fixed for tonight's game.

**Comment by ctm** [comment]
Fixed. Deploying now. There are two other bugs that contributed to this panic. I'll create separate issues for them.

This bug has been around for a very long time, it's just that the graphical interface drives the underlying API differently than most users of the text interface drive it.
