### ISSUE TITLE
cannot read property of 

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#801]
Fix regression that causes "cannot read property"

It happened to me when I logged in to check the state of tonight's game and it was reported in the lobby by many people.

This is weird because it didn't happen for this evening's game and nothing changed between the evening and night game. However, at least for now, it appears easy to reproduce, so I've labeled this issue as `easy`.

**Comment by ctm** [comment]
Oops. Looking at the timestamps in the lobby, it _did_ happen to others this evening. I didn't type anything in the nick box for the evening game, I used GitHub with a blank nick but for the night game I entered `dead 😴 head` (and auto-fill added a password, too).

My guess is something in my morning crate update broke it. I'll look at this tomorrow.

**Comment by ctm** [comment]
Ugh. This doesn't happen locally.

**Comment by ctm** [comment]
It only happens with auto-complete and auto-complete doesn't kick in (at least on Brave) with localhost, presumably because of the incorrect certificate. As far as I can tell, the backtrace does not include any of mb2's source:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at g (/235.mb2-web.js:1:12059)
    at Object.Ln (/235.mb2-web.js:1:23194)
    at __wbg_code_1c2fd251f38b398a (mb2-web.js:2:3280640)
    at web_sys::features::gen_KeyboardEvent::KeyboardEvent::code::h021bea3c598e84d1 (/mb2-web.wasm)
    at yew::html::component::scope::Scope<COMP>::callback_with_passive::{{closure}}::he60ab3fff4f359b7 (/mb2-web.wasm)
    at <yew::html::listener::events::onblur::Wrapper as yew::virtual_dom::listeners::Listener>::handle::h4e7e8c20207ef5e5 (/mb2-web.wasm)
    at yew::virtual_dom::listeners::Registry::run_handlers::{{closure}}::h26e47fc6e5fdf4ec (/mb2-web.wasm)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::haf9824e184b4ad5f (/mb2-web.wasm)
    at <dyn core::ops::function::Fn<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1644295e9d5f72aa (/mb2-web.wasm)
    at z (/235.mb2-web.js:1:15265)
```

So, we're back to the "what changed?" question.

**Comment by ctm** [comment]
Hmmm... my guess is that this portion of code from lobby.rs is being hit:
```
        let onkeyup = self.link.callback(move |e: KeyboardEvent| {
            if e.code() == "Enter" {
...
```

Furthermore, my guess is that `e` isn't a `KeyboardEvent`. Perhaps it's a `FocusEvent` (I see `onblur` deeper in the backtrace). I think I can add `gloo-console` and use `console_dbg` to find out.

**Comment by ctm** [comment]
Sure enough. Here's what we get on an error:
```
[front-ends/web/src/lobby.rs:1350] ::std::format!("{:?}", v) = KeyboardEvent { obj: UiEvent { obj: Event { obj: Object { obj: JsValue(Event) } } } }
```
and here's what we get on success:
```
[front-ends/web/src/lobby.rs:1350] ::std::format!("{:?}", v) = KeyboardEvent { obj: UiEvent { obj: Event { obj: Object { obj: JsValue(KeyboardEvent) } } } }
```
So, something is passing an `Event` rather than a `KeyboardEvent` into our `onkeyup` handler. Could it be corruption from something completely unrelated? That's my suspicion (fear).

I'll try deploying the same version that was used for Thursday's tournaments and see if the problem is still there.

**Comment by ctm** [comment]
I'm doing a git bisect, but it's painfully slow because I have to do a full deploy. I could probably speed it up by solving the localhost certificate issue, but I can sort of do the bisect in my sleep in that I'm going to go back to sleep now during this deploy and I'll check it when I wake up (which I do several times a night).

**Comment by ctm** [comment]
This regression crept in almost a week ago. It's weird that it got reported by multiple people on the same day I happened to get bitten myself. I'm deploying a potential fix:
```
        let onkeyup = self.link.callback(move |e: KeyboardEvent| {
            // TODO: I think someone else's bug is what requires us to
            // have this is_instance_of call.  Write a short demo and
            // then ask in Discord.
            if e.is_instance_of::<KeyboardEvent>() && e.code() == "Enter" {
                if let Some(enter) = enter_ref.cast::<HtmlButtonElement>() {
```
If my workaround works, I'll do what I mention in my comment and try to track down what's causing a keyup handler to be getting an `Event` rather than a `KeyboardEvent`.

**Comment by ctm** [comment]
My workaround works, so I created a separate issue (#802) to track down the cause.
