### ISSUE TITLE
Wonky Donkey crash

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#826]
Fix whatever caused the crash in this evening's (inaugural) Wonky Donkey tournament.

> Dealing #239492: 1200 2400 Wonky Donkey
```
2022-01-25T01:34:29.670770581Z thread '<unnamed>' panicked at 'should not get here', lib/commands/src/game/choice.rs:42:9
...
2022-01-25T01:34:30.490340279Z   15:     0x55cce91278a9 - <mb2_commands::game::choice::Choice as mb2_commands::game_group::GameGroup>::hand_winnings::h2f24444b58beea13
2022-01-25T01:34:30.490357339Z                                at /usr/src/poker/lib/commands/src/game/choice.rs:42:9
2022-01-25T01:34:30.551751310Z   16:     0x55cce905dfc7 - mb2::table::Table::showdown::hb250bb0ad75139c7
2022-01-25T01:34:30.551795490Z                                at /usr/src/poker/mb2/src/table.rs:2402:40
2022-01-25T01:34:30.551998043Z   17:     0x55cce905a29c - mb2::table::Table::deal::h6cdf245a95086b82
2022-01-25T01:34:30.552010343Z                                at /usr/src/poker/mb2/src/table.rs:1751:21
2022-01-25T01:34:30.567348976Z   18:     0x55cce8f24cf5 - <mb2::table::Table as mb2::table::NextActions>::continue_dealing::hd9af1c599ba7f7b2
2022-01-25T01:34:30.567380646Z                                at /usr/src/poker/mb2/src/table.rs:4632:9
```

**Comment by ctm** [comment]
> deadhead: FWIW, I know what caused it. The portion of the code that switches the game was bypassed due to all but one player being all-in.
deadhead: So the game was chosen and the cleanup code (that deals the extra two cards) was executed, but the last little bit was skipped.

**Comment by ctm** [comment]
Fixed. Deploying now.
```
diff --git a/mb2/src/table.rs b/mb2/src/table.rs
index ad8777e6..41fbe065 100644
--- a/mb2/src/table.rs
+++ b/mb2/src/table.rs
@@ -798,6 +798,13 @@ impl Table {
                 }
                 let desc = game.description().to_string();
                 self.upcoming_game = Some(game);
+                // If there's action possible, the game switch will be
+                // done later.  If there's no action possible we have
+                // to do it now so that the proper game will be in
+                // place for the showdown.
+                if !self.action_possible() {
+                    self.switch_to_upcoming_game();
+                }
```
