### ISSUE TITLE
gloo-timers 0.2.3 breaks mb2

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#834]
Deploy with gloo-timers 0.2.2 and contact the gloo folks with details.

I did my normal "blind deploy after upgrading crates" this morning and got a white screen. When I looked at the JavaScript console I saw a panic due to some sort of timer call. I didn't write it down (although I should have!). 

I've verified that gloo-timers 0.2.2 works and am doing a fresh build of that and a deploy now. Once my machine is freed up from the deploy, I'll go back to 0.2.3 and get the backtrace and report it on the gloo channel of the yew discord server.

FWIW, I briefly looked at the most recent commit to the gloo-timer code and the change was too large for me to identify the culprit, especially with me not having written down the panic backtrace and also due to the backtrace itself being a bit mangled (presumably due to some optimization settings).

**Comment by ctm** [comment]
Here's the backtrace (I still had the devtools window; it was just behind a bunch of other windows):
```
Uncaught (in promise) TypeError: Illegal invocation
    at __wbg_clearTimeout_d8b36ad8fa330187 (mb2-web.js:2:3273422)
    at 4352 (/mb2-web.wasm)
    at 1227 (/mb2-web.wasm)
    at 1094 (/mb2-web.wasm)
    at 2198 (/mb2-web.wasm)
    at 4222 (/mb2-web.wasm)
    at Module.B (/235.mb2-web.js:1:16016)
    at mb2-web.js:2:34857
```

**Comment by ctm** [comment]
Here's a much better backtrace:
```
mb2-web.js:2073 Uncaught (in promise) TypeError: Illegal invocation
    at __wbg_clearTimeout_d8b36ad8fa330187 (mb2-web.js:2073:86)
    at gloo_timers::callback::clear_timeout::hc9901ba06e5b915e (mb2-web.wasm:0x224a5ef)
    at <gloo_timers::callback::Timeout as core::ops::drop::Drop>::drop::h73b31e7ef0d81050 (mb2-web.wasm:0x20e5ee5)
    at core::ptr::drop_in_place<gloo_timers::callback::Timeout>::hab75f866a127e28e (mb2-web.wasm:0x2229a6b)
    at mb2_web::lobby::Lobby::ping_if_needed::hf6a508ca3239b3f0 (mb2-web.wasm:0x1b1ebf1)
    at <mb2_web::lobby::Lobby as yew::html::component::Component>::create::h7b3f769a06a3f5de (mb2-web.wasm:0xb6bd68)
    at yew::html::component::lifecycle::ComponentState<COMP>::new::he32da95cbb081231 (mb2-web.wasm:0x17614be)
    at <yew::html::component::lifecycle::CreateRunner<COMP> as yew::scheduler::Runnable>::run::ha7c0fb47cddec0ce (mb2-web.wasm:0x1761213)
    at yew::scheduler::start::{{closure}}::h33ce9613a2d0c9ba (mb2-web.wasm:0x18c0dc5)
    at std::thread::local::LocalKey<T>::try_with::h7c46966e94f3e796 (mb2-web.wasm:0x1fa2277)
```
I'm trying to reproduce this in a tiny app. One thing to note is that I believe (due to how quickly this panic shows up after mb2 loads) we're replacing the ping_timeout Timeout before the original one fires.

**Comment by ctm** [comment]
I haven't had any success building a tiny app, so now I'm hacking code out of lobby and looking to see when the bug goes away. One notable thing is that my tiny app was running under trunk, but mb2 runs under webpack. So, as I'm doing compiles of mb2, I'll also update my tiny app to use webpack.

**Comment by ctm** [comment]
I wound up creating [gloo-timers-regression](https://github.com/ctm/gloo-timers-regression) and submitted [an issue](https://github.com/rustwasm/gloo/issues/187). I've brought it to the attention of folks on the #gloo channel of the yew discord server.
