### ISSUE TITLE
observer load testing (up to 10,000 observers)

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#995]
Work on getting 10,000 observers on our t3a.micro instance.

I did a bunch of work yesterday to verify that observers are as lightweight as I thought. I actually had an unpleasant surprise, because there were places where a new observer would make one or more database calls, so simply firing up 500 observers caused a noticeable load. By the time I went to bed, however, I had gotten rid of those database calls, but&hellip;

I hadn't yet bumped up the maximum number of files mb2 could have open, nor did I do that on my laptop which is where it's easiest for me to run `websocket_tool`, the little app I used to get all the observers. Now that I've slept, I cranked those up, but when I try to get 2,000 observers, I get:
```
thread 'thread 'tokio-runtime-worker' panicked at 'could not connect: Tls(Native(Error { code: -9806, message: "connection closed via error" }))', websocket_tool/src/main.rs:51:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
tokio-runtime-worker' panicked at 'could not connect: Tls(Native(Error { code: -9806, message: "connection closed via error" }))', websocket_tool/src/main.rs:51:65
thread 'tokio-runtime-worker' panicked at 'could not connect: Tls(Native(Error { code: -9806, message: "connection closed via error" }))', websocket_tool/src/main.rs:51:65
thread 'tokio-runtime-worker' panicked at 'could not connect: Tls(Native(Error { code: -9806, message: "connection closed via error" }))', websocket_tool/src/main.rs:51:65
thread 'tokio-runtime-worker' panicked at 'could not connect: Tls(Native(Error { code: -9806, message: "connection closed via error" }))', websocket_tool/src/main.rs:51:65
thread 'tokio-runtime-worker' panicked at 'could not connect: Tls(Native(Error { code: -9806, message: "connection closed via error" }))', websocket_tool/src/main.rs:51:65
...
```
A web search suggests that this happens when there are network problems while doing the SSL connection handshake. Well, I'd actually prefer that my observers don't use `wss` since nothing sensitive is transmitted or received and some CPU time is expended doing that handshake, but although I was able to use `ws` in development, something about either how I have things configured via Cloudflare or via the load balancers prevents me from doing that with `devctm.com` right now.

So now I have a few related things to look into:

- [ ] can I simply run `websocket_tool` on either devctm.com or another EC2 instance and get rid of the `connection closed error`?
- [ ] [can I get my devctm.com network stack to allow observers to use ws](https://github.com/ctm/mb2-doc/issues/994)?
- [ ] will I hit any other speedbumps on my way to 10k observers?

I have not marked this as high priority because I'm sufficiently happy with the numbers I'm seeing when I get ~1,700 observers that I believe what we have now is exceedingly likely to handle 10k connections if they're all started around the same time but from different hosts. OTOH, even though it's not marked high priority, I'll play around a little more before mothballing this issue, just so I can get to a good stopping point.

**Comment by ctm** [comment]
I'm closing this issue, but leaving open the one for getting devctm.com to accept observers using `ws` instead of `wss` (#994).
